In [1]:
from finance_python.stock import stock
from finance_python.industry import industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
symbols = ['ATD-A.TO', 'DSG.TO', 'VFF.TO']

symbols = set(symbols)
symbols = list(symbols)
start = date.today() - timedelta(days=365)
end = date.today()

In [3]:
stock_loop = lambda x: stock(x, start, end)
stat = lambda x: stocks[x].stats()
bal = lambda x: stocks[x].balance()
fin = lambda x: stocks[x].financial()
ca = lambda x: stocks[x].cash()
an = lambda x: stocks[x].analyze()

In [4]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

17.697929859161377

In [5]:
timer_start = time.time()

for each in range(0, len(stocks)):
    stat(each)
    
timer_end = time.time()
print(timer_end - timer_start)

4.069112062454224

In [6]:
timer_start = time.time()

for each in range(0, len(stocks)):
    bal(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.28488826751709

In [7]:
timer_start = time.time()

for each in range(0, len(stocks)):
    fin(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.1612207889556885

In [8]:
timer_start = time.time()

for each in range(0, len(stocks)):
    ca(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.235023021697998

In [9]:
timer_start = time.time()

for each in range(0, len(stocks)):
    an(each)
    
timer_end = time.time()
print(timer_end - timer_start)

5.228779554367065

In [10]:
ATD, DSG, VFF = stocks

In [11]:
DSG.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list'],
 ['financials', 'fin_list'],
 ['cashflow', 'cash_list'],
 ['earnings_est',
  'revenue',
  'earnings_history',
  'eps_trend',
  'eps_revisions',
  'growth_estimates',
  'a_list']]

In [50]:
ATD.price

14.37

In [36]:
VFF.description

"The Descartes Systems Group Inc. provides federated network and logistics technology solutions worldwide. Its Logistics Application Suite offers a range of modular, cloud-based, and interoperable Web and wireless logistics management applications. The company's Logistics Application Suite offers solutions, such as route planning and execution, mobile applications, and telematics and compliance; transportation management solutions comprising carrier compliance and rate management, freight audit and settlement, dock scheduling and yard management, pool distribution, transportation planning and execution, and logistics flow control, as well as visibility, tracking, and performance management; and global logistics network services, such as document management, community, and connectivity services. Its Logistics Application Suite solutions also include customs and regulatory compliance solutions, such as cargo security compliance, declaration and fiscal compliance, customs warehouse management, ocean regulatory services, industry program support services, global trade content, and government solutions; and broker and forwarder enterprise system solutions, such as forwarder back office, and brokerage and declaration services. In addition, the company offers consulting, implementation, and training services; and maintenance and support services. It serves transportation providers, logistics service providers, and distribution-intensive companies through distributors, alliance partners, and value added resellers. The company was founded in 1981 and is headquartered in Waterloo, Canada."

In [14]:
VFF.sector

'Software - Application'

In [15]:
VFF.price

47.46

In [32]:
DSG.revenue

nan

In [17]:
VFF.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list'],
 ['financials', 'fin_list'],
 ['cashflow', 'cash_list'],
 ['earnings_est',
  'revenue',
  'earnings_history',
  'eps_trend',
  'eps_revisions',
  'growth_estimates',
  'a_list']]

In [49]:
VFF.cashflow.dropna()

Empty DataFrame
Columns: [Changes]
Index: []

In [19]:
portfolio = industry()

In [20]:
portfolio.statistics(ATD.stats_list)

In [21]:
portfolio.attributes

['cashflow()', 'balance_sheet()', 'financials()', 'analysis()', 'statistics']

In [22]:
portfolio.statistics.dropna(how='all')

,VFF.TO,ATD-A.TO,DSG.TO,Averages
Market Cap (intraday) 5,724.85,4563.00,404.00,1897.283333
Enterprise Value 3,739.73,NaN,NaN,739.730000
Trailing P/E,46.85,25.50,120.05,64.133333
Forward P/E 1,15.99,NaN,NaN,15.990000
Price/Sales (ttm),4.78,0.77,14.12,6.556667
Price/Book (mrq),5.40,5.24,6.75,5.796667
Enterprise Value/Revenue 3,4.88,0.92,13.59,6.463333
Enterprise Value/EBITDA 6,-80.93,15.43,40.37,-8.376667
Beta (3Y Monthly),5.14,0.30,1.23,2.223333
52-Week Change 3,107.66,29.69,3.24,46.863333
S&P500 52-Week Change 3,0.33,0.33,0.33,0.330000
52 Week High 3,24.25,88.70,56.01,56.320000
52 Week Low 3,3.98,59.65,33.96,32.530000
50-Day Moving Average 3,15.16,81.88,47.15,48.063333
200-Day Moving Average 3,16.23,80.80,49.36,48.796667
Shares Outstanding 5,49.28,126.91,84.12,86.770000
Float,38.64,439.12,76.93,184.896667
"Shares Short (Aug 15, 2019) 4",2.56,469.00,NaN,235.780000
"Short Ratio (Aug 15, 2019) 4",3.14,0.52,8.06,3.906667
"Short % of Shares Outstanding (Aug 15, 2019) 4",5.19,0.00,1.17,2.120000
"Shares Short (prior month Jul 15, 2019) 4",1.95,NaN,NaN,1.950000
Forward Annual Dividend Rate 4,NaN,0.50,NaN,0.500000
Forward Annual Dividend Yield 4,NaN,0.59,NaN,0.590000
Trailing Annual Dividend Rate 3,NaN,0.33,NaN,0.330000
Trailing Annual Dividend Yield 3,NaN,0.41,NaN,0.410000
5 Year Average Dividend Yield 4,NaN,0.48,NaN,0.480000
Payout Ratio 4,0.00,9.94,0.00,3.313333
Profit Margin,10.43,3.10,11.05,8.193333
Operating Margin (ttm),-10.82,4.31,16.91,3.466667
Return on Assets (ttm),-5.86,6.95,3.88,1.656667
Return on Equity (ttm),14.40,21.34,5.97,13.903333
Revenue (ttm),151.69,NaN,286.16,218.925000
Revenue Per Share (ttm),3.07,104.76,3.72,37.183333
Quarterly Revenue Growth (yoy),-1.70,-3.70,16.40,3.666667
Gross Profit (ttm),8.88,NaN,200.18,104.530000
EBITDA,-9.14,NaN,96.32,43.590000
Net Income Avi to Common (ttm),15.82,NaN,31.61,23.715000
Diluted EPS (ttm),0.31,3.25,0.40,1.320000
Quarterly Earnings Growth (yoy),NaN,-25.00,4.80,-10.100000
Total Cash (mrq),11.71,706.40,29.55,249.220000
Total Cash Per Share (mrq),0.24,1.25,0.38,0.623333
Total Debt (mrq),43.34,NaN,253.50,148.420000
Total Debt/Equity (mrq),32.31,78.48,46.17,52.320000
Current Ratio (mrq),2.42,0.77,0.94,1.376667
Book Value Per Share (mrq),2.72,15.81,7.11,8.546667
Operating Cash Flow (ttm),-4.43,NaN,82.66,39.115000
Levered Free Cash Flow (ttm),-12.05,NaN,75.93,31.940000

In [23]:
portfolio.cashflow(ATD.cash_list)

In [24]:
portfolio.attributes

['cashflow()',
 'balance_sheet()',
 'financials()',
 'analysis()',
 'statistics',
 'cashflow']

In [25]:
portfolio.cashflow.dropna(how='all')

                                              VFF.TO   ATD-A.TO  DSG.TO
Net Income                                 -3.457020   0.539540     NaN
Depreciation                               -0.151841   0.583497     NaN
Adjustments To Net Income                  -0.652582 -54.066667     NaN
Changes In Accounts Receivables            -2.916667  -0.248598     NaN
Changes In Liabilities                     -1.490129 -43.895833     NaN
Changes In Inventories                     -4.509014  -6.113360     NaN
Changes In Other Operating Activities      -3.622222  13.800000     NaN
Total Cash Flow From Operating Activities  -1.307410   0.633349     NaN
Capital Expenditure                         0.490602   0.264326     NaN
Other Cash flows from Investing Activities -0.000000 -43.250000     NaN
Total Cash Flows From Investing Activities  5.501205  -0.208330     NaN
Dividends Paid                                   NaN   0.741595     NaN
Net Borrowings                             -0.824208   1.434113     NaN
Other Cash Flows from Financing Activities  0.067108  20.422018     NaN
Total Cash Flows From Financing Activities -4.103438   1.923143     NaN
Effect Of Exchange Rate Changes            -0.928571  -3.775510     NaN
Change In Cash and Cash Equivalents        -4.499275   0.703390     NaN

In [26]:
portfolio.financials(ATD.fin_list)

In [27]:
portfolio.financials

                                          VFF.TO  ATD-A.TO  DSG.TO
Total Revenue                           0.056829  0.731389     NaN
Cost of Revenue                         0.117697  0.778945     NaN
Gross Profit                           -0.433346  0.511946     NaN
Selling General and Administrative      0.291881  0.481009     NaN
Total Operating Expenses                0.132869  0.741463     NaN
Operating Income or Loss               -2.838656  0.534197     NaN
Total Other Income/Expenses Net        -0.650982  4.068768     NaN
Earnings Before Interest and Taxes     -2.838656  0.534197     NaN
Interest Expense                        0.204787  2.118474     NaN
Income Before Tax                      -9.167203  0.379002     NaN
Income Tax Expense                      1.131783 -0.068792     NaN
Minority Interest                            NaN -0.211315     NaN
Net Income From Continuing Ops         -3.457020  0.528706     NaN
Net Income                             -3.457020  0.539540     NaN
Net Income                             -3.457020  0.539540     NaN
Net Income Applicable To Common Shares -3.457020  0.539540     NaN

In [28]:
portfolio.balance_sheet(ATD.bs_list)

In [29]:
portfolio.balance_sheet

                                     VFF.TO   ATD-A.TO  DSG.TO
Cash And Cash Equivalents          1.404680   0.178512     NaN
Net Receivables                    1.351029   0.444452     NaN
Inventory                          0.378483   0.797110     NaN
Other Current Assets              37.807339  20.470588     NaN
Total Current Assets               0.813267   0.499514     NaN
Long Term Investments                   NaN   0.434286     NaN
Property, plant and equipment     -0.178247   0.746826     NaN
Goodwill                                NaN   2.204997     NaN
Intangible Assets                       NaN   0.249372     NaN
Other Assets                       0.451019  -0.018338     NaN
Deferred Long Term Asset Charges        NaN   0.866091     NaN
Total Assets                       0.229252   0.843300     NaN
Accounts Payable                   0.648527   0.789544     NaN
Short/Current Long Term Debt      -0.221969  44.528662     NaN
Other Current Liabilities               NaN   0.620500     NaN
Total Current Liabilities          0.425414   1.098654     NaN
Long Term Debt                    -0.269717   0.905764     NaN
Other Liabilities                 -0.511995   0.349335     NaN
Total Liabilities                 -0.118666   0.858687     NaN
Common Stock                       1.444364   0.010003     NaN
Retained Earnings                 -0.095264   0.803522     NaN
Treasury Stock                    -7.244186   0.235362     NaN
Capital Surplus                    0.836257   0.317568     NaN
Other Stockholder Equity          -7.244186   0.235362     NaN
Total stockholders' equity         0.600102   0.770090     NaN
Net Tangible Assets                0.600102  -0.086107     NaN