In [1]:
from finance_python.stock import stock
from finance_python.industry import industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
symbols = [ 'RBS', 'ORAN', 'LMRK', 'GSBD', 'GILT']
start = date.today() - timedelta(days=365)
end = date.today()

In [3]:
stock_loop = lambda x: stock(x, start, end)
stat = lambda x: stocks[x].stats()
bal = lambda x: stocks[x].balance()
fin = lambda x: stocks[x].financial()
ca = lambda x: stocks[x].cash()
an = lambda x: stocks[x].analyze()

In [4]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

18.01914668083191

In [5]:
timer_start = time.time()

for each in range(0, len(stocks)):
    stat(each)
    
timer_end = time.time()
print(timer_end - timer_start)

3.2746782302856445

In [6]:
timer_start = time.time()

for each in range(0, len(stocks)):
    bal(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.426229476928711

In [7]:
timer_start = time.time()

for each in range(0, len(stocks)):
    fin(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.7278249263763428

In [8]:
timer_start = time.time()

for each in range(0, len(stocks)):
    ca(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.411168336868286

In [9]:
timer_start = time.time()

for each in range(0, len(stocks)):
    an(each)
    
timer_end = time.time()
print(timer_end - timer_start)

5.919370174407959

In [11]:
RBS, ORAN, LMRK, GSBD, GILT = stocks

In [12]:
price = list(map(lambda symbol, x: {symbol: stocks[x].price}, symbols, range(0, len(symbols))))

In [13]:
price

[{'RBS': 4.51},
 {'ORAN': 15.26},
 {'LMRK': 15.44},
 {'GSBD': 19.99},
 {'GILT': 7.94}]

In [15]:
RBS.description

'The Royal Bank of Scotland Group plc, together with its subsidiaries, provides banking and financial products and services to personal, commercial, corporate, and institutional customers worldwide. It operates through Personal  Business Banking, Commercial  Private Banking, RBS International, and NatWest Markets segments. The company also offers wealth management, financial planning, investment management, asset finance, and offshore banking; and financing and risk solutions, as well as trading and flow sales services. The Royal Bank of Scotland Group plc was founded in 1727 and is headquartered in Edinburgh, the United Kingdom.'

In [18]:
LMRK.earnings_history

                  9/29/2018 12/30/2018 3/30/2019 6/29/2019
Earnings History
EPS Est.               0.13       0.12      0.19       0.1
EPS Actual             3.71      -0.21      0.15      0.23
Difference             3.58      -0.33     -0.04      0.13
Surprise %        2,753.80%   -275.00%   -21.10%   130.00%

In [20]:
RBS.statistics.dropna()

                                                      RBS
Market Cap (intraday) 5                         2835.0000
Trailing P/E                                      28.3100
Price/Book (mrq)                                   0.4500
Beta (3Y Monthly)                                  1.0900
52-Week Change 3                                 -30.7200
S&P500 52-Week Change 3                            2.0800
52 Week High 3                                     7.3100
52 Week Low 3                                      4.3300
50-Day Moving Average 3                            5.0186
200-Day Moving Average 3                           5.9555
Avg Vol (10 day) 3                                 1.0100
% Held by Insiders 1                               0.0000
% Held by Institutions 1                           0.5500
Shares Short (Aug 15, 2019) 4                      2.7500
Short Ratio (Aug 15, 2019) 4                       3.0500
Short % of Shares Outstanding (Aug 15, 2019) 4     0.0500
Shares Short (prior month Jul 15, 2019) 4          2.7700
Forward Annual Dividend Rate 4                     0.1000
Forward Annual Dividend Yield 4                    2.1700
Trailing Annual Dividend Rate 3                    0.0300
Trailing Annual Dividend Yield 3                   0.5800
Payout Ratio 4                                    57.1300
Profit Margin                                     27.4700
Operating Margin (ttm)                             0.0000
Return on Assets (ttm)                             0.4800
Return on Equity (ttm)                             7.4600
Quarterly Revenue Growth (yoy)                   -14.5000
Diluted EPS (ttm)                                  0.1660
Quarterly Earnings Growth (yoy)                  497.1000

In [23]:
LMRK.dividends

[                                                Date        Dividends
 0                                       Aug 01, 2019   0.368 Dividend
 1                                       Apr 30, 2019  0.3675 Dividend
 2                                       Feb 01, 2019  0.3675 Dividend
 3                                       Nov 02, 2018  0.3675 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...              NaN]

In [24]:
LMRK.cashflow.dropna()

Period Ending,12/31/2018,12/31/2017,12/31/2016,12/31/2015,Changes
LMRK,,,,,
Net Income,115010.0,18769.0,9811.0,1205.0,94.443983
Depreciation,14926.0,12311.0,9853.0,7184.0,1.077673
Adjustments To Net Income,-98293.0,-2.0,659.0,6055.0,-17.233361
Changes In Accounts Receivables,-3.0,-2338.0,-1731.0,-1520.0,-0.998026
Changes In Liabilities,-156.0,-289.0,810.0,2891.0,-1.053961
Changes In Other Operating Activities,-4037.0,-2215.0,360.0,-1762.0,1.291146
Total Cash Flow From Operating Activities,31256.0,28473.0,21465.0,15955.0,0.959010
Other Cash flows from Investing Activities,1108.0,-3209.0,-9267.0,562.0,0.971530
Total Cash Flows From Investing Activities,-37533.0,-140128.0,-156468.0,-134211.0,-0.720343
Dividends Paid,-47731.0,-38711.0,-24395.0,-10797.0,3.420765
Net Borrowings,13720.0,155908.0,31266.0,122182.0,-0.887709
Other Cash Flows from Financing Activities,-27989.0,-19216.0,8139.0,-38398.0,-0.271082
Total Cash Flows From Financing Activities,-13652.0,133981.0,138649.0,119929.0,-1.113834
Effect Of Exchange Rate Changes,-151.0,-28.0,-68.0,-68.0,1.220588
Change In Cash and Cash Equivalents,-20080.0,22298.0,3578.0,1673.0,-13.002391

In [25]:
portfolio = industry()

In [26]:
portfolio.statistics(LMRK.stats_list)

In [27]:
4/LMRK.price

0.2590673575129534

In [28]:
.38/GILT.price

0.04785894206549118

In [29]:
portfolio.statistics.dropna(how='all')

,RBS,ORAN,LMRK,GSBD,GILT,Averages
% Held by Insiders 1,0.0000,0.00,19.95,0.31,49.71,13.994000
% Held by Institutions 1,0.5500,1.46,25.18,36.56,13.91,15.532000
200-Day Moving Average 3,5.9555,15.48,15.82,20.17,8.58,13.201100
5 Year Average Dividend Yield 4,NaN,4.68,NaN,NaN,NaN,4.680000
50-Day Moving Average 3,5.0186,14.88,16.28,19.83,8.33,12.867720
52 Week High 3,7.3100,17.06,17.54,22.75,10.74,15.080000
52 Week Low 3,4.3300,14.57,10.32,17.73,7.60,10.910000
52-Week Change 3,-30.7200,-2.93,19.23,-8.80,-15.05,-7.654000
Avg Vol (10 day) 3,1.0100,NaN,NaN,NaN,NaN,1.010000
Beta (3Y Monthly),1.0900,0.14,1.18,1.03,0.38,0.764000
Book Value Per Share (mrq),NaN,NaN,15.74,17.21,4.03,12.326667
Current Ratio (mrq),NaN,NaN,2.58,0.86,1.68,1.706667
Diluted EPS (ttm),0.1660,0.88,4.01,0.90,0.36,1.263200
EBITDA,NaN,NaN,50.84,NaN,34.36,42.600000
Enterprise Value 3,NaN,NaN,751.64,NaN,415.08,583.360000
Enterprise Value/EBITDA 6,NaN,NaN,14.78,NaN,12.08,13.430000
Enterprise Value/Revenue 3,NaN,NaN,12.15,10.99,1.63,8.256667
Float,NaN,NaN,21.67,NaN,27.26,24.465000
Forward Annual Dividend Rate 4,0.1000,0.79,1.47,1.80,0.45,0.922000
Forward Annual Dividend Yield 4,2.1700,5.21,9.74,9.08,5.56,6.352000
Forward P/E 1,NaN,NaN,25.34,10.32,NaN,17.830000
Gross Profit (ttm),NaN,NaN,60.39,146.73,94.04,100.386667
Levered Free Cash Flow (ttm),NaN,NaN,24.50,50.66,14.85,30.003333
Market Cap (intraday) 5,2835.0000,4027.00,411.25,812.00,457.39,1708.528000
Net Income Avi to Common (ttm),NaN,NaN,106.51,36.10,20.18,54.263333
Operating Cash Flow (ttm),NaN,NaN,26.57,-266.10,11.16,-76.123333
Operating Margin (ttm),0.0000,0.00,59.75,80.25,8.99,29.798000
PEG Ratio (5 yr expected) 1,NaN,NaN,5.32,16.88,NaN,11.100000
Payout Ratio 4,57.1300,99.07,36.39,197.80,125.00,103.078000
Price/Book (mrq),0.4500,1.14,1.00,1.17,2.05,1.162000
Price/Sales (ttm),NaN,NaN,6.65,5.45,1.80,4.633333
Profit Margin,27.4700,5.29,191.77,24.25,7.93,51.342000
Quarterly Earnings Growth (yoy),497.1000,31.70,53.50,-7.70,58.30,126.580000
Quarterly Revenue Growth (yoy),-14.5000,1.50,-9.60,3.10,-10.30,-5.960000
Return on Assets (ttm),0.4800,3.08,2.77,5.28,3.87,3.096000
Return on Equity (ttm),7.4600,7.37,34.83,5.09,9.04,12.758000
Revenue (ttm),NaN,NaN,61.86,148.89,254.30,155.016667
Revenue Per Share (ttm),NaN,NaN,2.45,3.70,4.61,3.586667
S&P500 52-Week Change 3,2.0800,2.08,2.08,2.08,2.08,2.080000
Shares Outstanding 5,NaN,NaN,25.34,40.34,55.44,40.373333
"Shares Short (Aug 15, 2019) 4",2.7500,NaN,NaN,NaN,NaN,2.750000
"Shares Short (prior month Jul 15, 2019) 4",2.7700,NaN,NaN,NaN,NaN,2.770000
"Short % of Float (Aug 15, 2019) 4",NaN,NaN,0.23,1.11,0.02,0.453333
"Short % of Shares Outstanding (Aug 15, 2019) 4",0.0500,0.00,0.20,0.93,0.01,0.238000
"Short Ratio (Aug 15, 2019) 4",3.0500,0.10,0.59,3.44,0.54,1.544000
Total Cash (mrq),NaN,NaN,12.11,10.12,39.90,20.710000
Total Cash Per Share (mrq),NaN,NaN,0.48,0.25,0.72,0.483333
Total Debt (mrq),NaN,NaN,398.64,842.82,13.08,418.180000
Total Debt/Equity (mrq),NaN,NaN,104.52,121.54,5.86,77.306667
Trailing Annual Dividend Rate 3,0.0300,0.81,1.47,1.80,0.45,0.912000
Trailing Annual Dividend Yield 3,0.5800,5.34,9.52,9.00,5.70,6.028000
Trailing P/E,28.3100,17.25,3.92,22.44,22.98,18.980000

In [31]:
portfolio.cashflow(LMRK.cash_list)

In [32]:
portfolio.cashflow.dropna(how='all')

,RBS,ORAN,LMRK,GSBD,GILT
Adjustments To Net Income,-0.049891,4.488889,-17.233361,-0.284317,-1.071575
Capital Expenditure,-0.209451,-0.016600,NaN,NaN,1.737659
Change In Cash and Cash Equivalents,2.198980,-0.923547,-13.002391,-1.389547,-2.877839
Changes In Accounts Receivables,NaN,-2.634615,-0.998026,-1.372215,1.875027
Changes In Inventories,NaN,2.166667,NaN,NaN,-3.035803
Changes In Liabilities,NaN,1.058140,-1.053961,NaN,-0.953084
Changes In Other Operating Activities,-1.300601,-1.951351,1.291146,-1.777044,-0.775950
Depreciation,-0.060411,0.090023,1.077673,NaN,-0.127588
Dividends Paid,0.846753,-0.000537,3.420765,0.107052,NaN
Effect Of Exchange Rate Changes,0.173611,-0.923077,1.220588,0.000000,0.525077
Investments,0.208312,-4.748634,NaN,NaN,NaN
Net Borrowings,-0.258943,-1.291126,-0.887709,0.712594,-0.595475
Net Income,-2.354454,-0.263198,94.443983,0.151197,-1.351760
Other Cash Flows from Financing Activities,-0.790282,-1.155528,-0.271082,-0.058577,NaN
Other Cash flows from Investing Activities,NaN,-1.152542,0.971530,NaN,NaN
Total Cash Flow From Operating Activities,-0.821723,-0.002204,0.959010,-0.594421,-3.165213
Total Cash Flows From Financing Activities,-0.675528,-0.711774,-1.113834,-0.677168,-0.604397
Total Cash Flows From Investing Activities,0.634813,-0.090793,-0.720343,NaN,-1.871880

In [34]:
portfolio.balance_sheet(LMRK.bs_list)

In [35]:
portfolio.balance_sheet.dropna(how='all')

,RBS,ORAN,LMRK,GSBD,GILT
Accounts Payable,0.022876,0.081741,3.160604,NaN,0.431493
Capital Surplus,-0.959607,0.004110,NaN,0.114669,0.046068
Cash And Cash Equivalents,0.044866,0.260685,1.070565,-0.730823,2.655058
Common Stock,0.036473,0.004153,1.005776,0.111111,0.281738
Deferred Long Term Asset Charges,-0.463322,-0.437860,NaN,NaN,NaN
Deferred Long Term Liability Charges,NaN,NaN,0.796764,-0.030130,NaN
Goodwill,0.008636,0.003805,NaN,NaN,0.000000
Intangible Assets,0.031665,-0.017729,0.588338,NaN,-0.858109
Inventory,NaN,0.264744,NaN,NaN,-0.167561
Long Term Debt,0.210078,-0.090060,0.230966,0.573033,-0.623226
Long Term Investments,0.243723,0.834786,5.923039,NaN,NaN
Minority Interest,0.053073,0.093220,2.502152,NaN,NaN
Net Receivables,-0.788571,0.790459,1.478576,-0.249313,0.807250
Net Tangible Assets,-0.162151,0.008293,1.019612,0.030846,0.644560
Other Assets,-0.015583,-0.382903,2.350012,0.270440,1.306986
Other Current Assets,0.845816,-0.829863,NaN,-0.991203,-0.529554
Other Current Liabilities,0.902185,0.728194,NaN,0.107969,-0.673475
Other Liabilities,0.767261,-0.182625,-0.290746,NaN,-0.370515
Other Stockholder Equity,-0.095346,-0.215004,-351.750000,NaN,0.443520
"Property, plant and equipment",0.219793,0.102297,0.414839,NaN,0.029770
Retained Earnings,-4.560199,-0.344148,NaN,1.972197,-0.030291
Short Term Investments,-0.289536,-0.957911,NaN,NaN,NaN
Short/Current Long Term Debt,-0.969734,0.556657,NaN,NaN,-0.018494
Total Assets,-0.148604,0.056458,0.619815,0.233251,0.064487
Total Current Assets,-0.291938,0.089104,3.870837,-0.653983,0.117157
Total Current Liabilities,-0.190190,0.400906,4.266928,0.114461,-0.121584
Total Liabilities,-0.149116,0.089060,0.223517,0.547107,-0.192352
Total stockholders' equity,-0.140753,-0.007701,0.992010,0.030846,0.342483
Treasury Stock,-0.091593,-0.215004,-351.750000,NaN,0.443520

In [37]:
portfolio.financials(LMRK.fin_list)

In [38]:
portfolio.financials.dropna(how='all')

,RBS,ORAN,LMRK,GSBD,GILT
Total Revenue,-0.090863,0.028457,0.929458,0.238905,0.348522
Cost of Revenue,NaN,0.034920,-0.021624,NaN,0.202598
Gross Profit,-0.090863,0.018136,1.077757,0.238905,0.734200
Research Development,NaN,NaN,NaN,NaN,0.473452
Selling General and Administrative,-0.233481,0.008942,0.618543,0.105660,-0.068835
Others,NaN,0.031690,NaN,NaN,NaN
Total Operating Expenses,-0.233481,0.043466,0.571899,0.105660,0.176154
Operating Income or Loss,1.634652,-0.070218,1.258704,0.289582,-2.960936
Total Other Income/Expenses Net,-1.149004,-0.316303,-5.699804,0.432858,-0.892791
Earnings Before Interest and Taxes,NaN,-0.070218,1.258704,0.289582,-2.960936
Interest Expense,NaN,-0.186589,1.039898,1.538182,-0.601040
Income Before Tax,-2.242693,0.097499,95.305394,0.172104,-1.333425
Income Tax Expense,51.521739,1.016949,NaN,2.054054,-2.195798
Minority Interest,0.053073,0.093220,2.502152,NaN,NaN
Net Income From Continuing Ops,-1.789068,-0.140239,95.117012,0.151197,-1.353109
Net Income,-2.354454,-0.263198,94.443983,0.151197,-1.351760
Net Income,-2.354454,-0.263198,94.443983,0.151197,-1.351760
Net Income Applicable To Common Shares,-1.819606,-0.296186,140.820652,0.151197,-1.351760