In [1]:
from finance_python import stock, sector, industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
def print_mult(item):
    for each in item:
        print(each, '\n', '--------------')

In [3]:
energy = sector('energy')

In [4]:
symbols = ['NFLX', 'AAPL', 'BCE.TO', 'T', 'CMCSA']

start = date.today() - timedelta(days=365)
end = date.today()

In [5]:
stock_loop = lambda x: stock(x, start, end)
stat = lambda x: stocks[x].stats()
bal = lambda x: stocks[x].balance()
fin = lambda x: stocks[x].financial()
ca = lambda x: stocks[x].cash()
an = lambda x: stocks[x].analyze()

In [6]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

40.252819776535034

In [7]:
timer_start = time.time()

for each in range(0, len(stocks)):
    stat(each)
    
timer_end = time.time()
print(timer_end - timer_start)

3.7169189453125

In [8]:
timer_start = time.time()

for each in range(0, len(stocks)):
    bal(each)
    
timer_end = time.time()
print(timer_end - timer_start)

3.7887215614318848

In [9]:
timer_start = time.time()

for each in range(0, len(stocks)):
    fin(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.7994611263275146

In [10]:
timer_start = time.time()

for each in range(0, len(stocks)):
    ca(each)
    
timer_end = time.time()
print(timer_end - timer_start)

3.169316291809082

In [11]:
timer_start = time.time()

for each in range(0, len(stocks)):
    an(each)
    
timer_end = time.time()
print(timer_end - timer_start)

11.148953676223755

In [13]:
NFLX, AAPL, BCE, T, CMCSA = stocks

In [14]:
price = list(map(lambda symbol, x: {symbol: stocks[x].price}, symbols, range(0, len(symbols))))

In [15]:
price

[{'NFLX': 286.6},
 {'AAPL': 220.96},
 {'BCE.TO': 63.69},
 {'T': 37.15},
 {'CMCSA': 46.68}]

In [17]:
NFLX.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,38.00,35.00,40.00,39.00
Avg. Estimate,1.04,0.84,3.26,5.68
Low Estimate,0.98,0.66,3.10,3.53
High Estimate,1.18,1.39,3.93,6.81
Year Ago EPS,0.89,0.30,2.68,3.26

In [22]:
CMCSA.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,25.00,22.00,28.00,30.00
Avg. Estimate,0.76,0.78,3.07,3.41
Low Estimate,0.70,0.65,2.89,2.99
High Estimate,0.83,0.89,3.26,3.72
Year Ago EPS,0.65,0.64,2.55,3.07

In [21]:
T.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,21.00,19.00,27.00,27.00
Avg. Estimate,0.93,0.89,3.56,3.62
Low Estimate,0.90,0.85,3.24,2.74
High Estimate,0.98,0.97,3.72,4.03
Year Ago EPS,0.90,0.86,3.52,3.56

In [18]:
AAPL.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,34.00,30.00,38.00,39.00
Avg. Estimate,2.82,4.42,11.66,12.73
Low Estimate,2.72,3.75,11.50,10.62
High Estimate,2.93,4.87,11.80,14.25
Year Ago EPS,2.91,4.18,11.91,11.66

In [20]:
BCE.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,12.00,11.00,18.00,18.00
Avg. Estimate,0.93,0.90,3.54,3.71
Low Estimate,0.85,0.85,3.43,3.57
High Estimate,0.96,1.01,3.64,3.97
Year Ago EPS,0.96,0.89,3.51,3.54

In [19]:
BCE.statistics.dropna(how='all')

                                                     BCE.TO
Market Cap (intraday) 5                         5733.000000
Enterprise Value 3                              8847.000000
Trailing P/E                                      19.600000
Forward P/E 1                                     17.170000
PEG Ratio (5 yr expected) 1                        4.840000
Price/Sales (ttm)                                  2.410000
Price/Book (mrq)                                   3.550000
Enterprise Value/Revenue 3                         3.720000
Enterprise Value/EBITDA 6                          9.740000
Beta (3Y Monthly)                                  0.540000
52-Week Change 3                                  22.440000
S&P500 52-Week Change 3                            3.400000
52 Week High 3                                    64.500000
52 Week Low 3                                     50.720000
50-Day Moving Average 3                           62.300000
200-Day Moving Average 3                          60.630000
Avg Vol (3 month) 3                                1.470000
Avg Vol (10 day) 3                                 2.310000
Shares Outstanding 5                             900.100000
Float                                            899.450000
Shares Short (Aug 30, 2019) 4                     28.340000
Short Ratio (Aug 30, 2019) 4                      22.000000
Short % of Shares Outstanding (Aug 30, 2019) 4     3.150000
Shares Short (prior month Jul 31, 2019) 4         27.570000
Forward Annual Dividend Rate 4                     3.170000
Forward Annual Dividend Yield 4                    4.950000
Trailing Annual Dividend Rate 3                    3.100000
Trailing Annual Dividend Yield 3                   4.870000
5 Year Average Dividend Yield 4                    4.840000
Payout Ratio 4                                    95.230000
Profit Margin                                     12.920000
Operating Margin (ttm)                            23.410000
Return on Assets (ttm)                             5.950000
Return on Equity (ttm)                            15.140000
Revenue (ttm)                                   2376.000000
Revenue Per Share (ttm)                           26.440000
Quarterly Revenue Growth (yoy)                     2.500000
Gross Profit (ttm)                               982.000000
EBITDA                                           908.000000
Net Income Avi to Common (ttm)                   292.000000
Diluted EPS (ttm)                                  3.250000
Quarterly Earnings Growth (yoy)                    8.100000
Total Cash (mrq)                                 109.000000
Total Cash Per Share (mrq)                         1.220000
Total Debt (mrq)                                2763.000000
Total Debt/Equity (mrq)                          135.010000
Current Ratio (mrq)                                0.570000
Book Value Per Share (mrq)                        17.920000
Operating Cash Flow (ttm)                        744.000000
Adjusted Returns                                   9.166667
Total Returns                                     27.390000

In [23]:
basic_df = lambda x: {'symbol': symbols[x], 'price': stocks[x].price, 'description': stocks[x].description, 'sector': stocks[x].sector}

In [24]:
dict = list(map(basic_df, range(0, len(stocks))))
df = DataFrame(dict)
df.sort_values('sector')

,description,price,sector,symbol
1,"Apple Inc. designs, manufactures, and markets ...",220.96,Consumer Electronics,AAPL
0,"Netflix, Inc. provides Internet entertainment ...",286.60,Media - Diversified,NFLX
4,Comcast Corporation operates as a media and te...,46.68,Pay TV,CMCSA
2,"BCE Inc., a telecommunications and media compa...",63.69,Telecom Services,BCE.TO
3,"ATT Inc. provides telecommunication, media, an...",37.15,Telecom Services,T

In [26]:
AAPL.balance_sheet.dropna(how='all')

Period Ending,9/29/2018,9/30/2017,9/24/2016,9/26/2015,Changes
AAPL,,,,,
Cash And Cash Equivalents,25913000.0,20289000.0,20484000.0,21120000.0,0.226941
Short Term Investments,40388000.0,53892000.0,46671000.0,20481000.0,0.971974
Net Receivables,48995000.0,35673000.0,29299000.0,30343000.0,0.614705
Inventory,3956000.0,4855000.0,2132000.0,2349000.0,0.684121
Other Current Assets,12087000.0,13936000.0,8283000.0,14691000.0,-0.177251
Total Current Assets,131339000.0,128645000.0,106869000.0,89378000.0,0.469478
Long Term Investments,170799000.0,194714000.0,170430000.0,164065000.0,0.041045
"Property, plant and equipment",41304000.0,33783000.0,27010000.0,22471000.0,0.838102
Goodwill,NaN,NaN,5414000.0,5116000.0,NaN
Intangible Assets,NaN,NaN,3206000.0,3893000.0,NaN
Other Assets,22283000.0,18177000.0,8757000.0,5422000.0,3.109738
Total Assets,365725000.0,375319000.0,321686000.0,290345000.0,0.259622
Accounts Payable,55888000.0,44242000.0,37294000.0,35490000.0,0.574753
Short/Current Long Term Debt,8784000.0,6496000.0,3500000.0,2513000.0,2.495424
Other Current Liabilities,40230000.0,38099000.0,8243000.0,10939000.0,2.677667
Total Current Liabilities,116866000.0,100814000.0,79006000.0,80610000.0,0.449770
Long Term Debt,93735000.0,97207000.0,75427000.0,53329000.0,0.757674
Other Liabilities,47977000.0,43251000.0,39004000.0,37051000.0,0.294891
Total Liabilities,258578000.0,241272000.0,193437000.0,170990000.0,0.512240
Common Stock,40201000.0,35867000.0,31251000.0,27416000.0,0.466334
Retained Earnings,70400000.0,98330000.0,96364000.0,92284000.0,-0.237138
Treasury Stock,-3454000.0,-150000.0,634000.0,-345000.0,9.011594
Other Stockholder Equity,-3454000.0,-150000.0,634000.0,-345000.0,9.011594
Total stockholders' equity,107147000.0,134047000.0,128249000.0,119355000.0,-0.102283
Net Tangible Assets,107147000.0,134047000.0,119629000.0,110346000.0,-0.028991

In [28]:
NFLX.balance_sheet.dropna()

Period Ending,12/31/2018,12/31/2017,12/31/2016,12/31/2015,Changes
NFLX,,,,,
Cash And Cash Equivalents,3794483.0,2822795.0,1467576.0,1809330.0,1.097176
Other Current Assets,5899652.0,4847179.0,3986509.0,3121125.0,0.890233
Total Current Assets,9694135.0,7669974.0,5720291.0,5431840.0,0.784687
"Property, plant and equipment",418281.0,319404.0,250395.0,173412.0,1.412065
Intangible Assets,14960954.0,10371055.0,7274501.0,4312817.0,2.468952
Other Assets,901030.0,652309.0,339906.0,284802.0,2.163707
Deferred Long Term Asset Charges,564425.0,478266.0,227248.0,180573.0,2.125744
Total Assets,25974400.0,19012742.0,13586610.0,10202871.0,1.545793
Accounts Payable,562985.0,359555.0,312842.0,253491.0,1.220927
Other Current Liabilities,5446918.0,4791663.0,4076183.0,3135744.0,0.737042
Total Current Liabilities,6487320.0,5466312.0,4586657.0,3529624.0,0.837963
Long Term Debt,10360058.0,6499432.0,3364311.0,2371362.0,3.368822
Other Liabilities,3888257.0,3465042.0,2955842.0,2078459.0,0.870740
Total Liabilities,20735635.0,15430786.0,10906810.0,7979445.0,1.598631
Common Stock,2315988.0,1871396.0,1599762.0,1324809.0,0.748167
Retained Earnings,2942359.0,1731117.0,1128603.0,941925.0,2.123772
Treasury Stock,-19582.0,-20557.0,-48565.0,-43308.0,-0.547843
Other Stockholder Equity,-19582.0,-20557.0,-48565.0,-43308.0,-0.547843
Total stockholders' equity,5238765.0,3581956.0,2679800.0,2223426.0,1.356168
Net Tangible Assets,-9722189.0,-6789099.0,-4594701.0,-2089391.0,3.653121

In [29]:
BCE.dividends

[                                                Date        Dividends
 0                                       Sep 13, 2019   0.793 Dividend
 1                                       Jun 13, 2019  0.7925 Dividend
 2                                       Mar 14, 2019  0.7925 Dividend
 3                                       Dec 13, 2018   0.755 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...              NaN]

In [32]:
CMCSA.dividends

[                                                Date      Dividends
 0                                       Jul 02, 2019  0.21 Dividend
 1                                       Apr 02, 2019  0.21 Dividend
 2                                       Dec 31, 2018  0.19 Dividend
 3                                       Oct 02, 2018  0.19 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...            NaN]

In [33]:
T.dividends

[                                                Date      Dividends
 0                                       Jul 09, 2019  0.51 Dividend
 1                                       Apr 09, 2019  0.51 Dividend
 2                                       Jan 09, 2019  0.51 Dividend
 3                                       Oct 09, 2018   0.5 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...            NaN]

In [31]:
AAPL.dividends

[                                                Date      Dividends
 0                                       Aug 09, 2019  0.77 Dividend
 1                                       May 10, 2019  0.77 Dividend
 2                                       Feb 08, 2019  0.73 Dividend
 3                                       Nov 08, 2018  0.73 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...            NaN]

In [34]:
AAPL.cashflow.dropna()

Period Ending,9/29/2018,9/30/2017,9/24/2016,9/26/2015,Changes
AAPL,,,,,
Net Income,59531000.0,48351000.0,45687000.0,53394000.0,0.114938
Depreciation,10903000.0,10157000.0,10505000.0,11257000.0,-0.031447
Adjustments To Net Income,-27694000.0,10640000.0,9634000.0,5353000.0,-6.173548
Changes In Accounts Receivables,-5322000.0,-2093000.0,527000.0,417000.0,-13.762590
Changes In Liabilities,9131000.0,8340000.0,563000.0,6043000.0,0.511004
Changes In Inventories,828000.0,-2723000.0,217000.0,-238000.0,-4.478992
Changes In Other Operating Activities,30057000.0,-8447000.0,-902000.0,5040000.0,4.963690
Total Cash Flow From Operating Activities,77434000.0,64225000.0,66231000.0,81266000.0,-0.047154
Capital Expenditure,-13313000.0,-12451000.0,-12734000.0,-11247000.0,0.183693
Investments,30845000.0,-33542000.0,-32022000.0,-44417000.0,-1.694441
Other Cash flows from Investing Activities,-745000.0,-124000.0,-924000.0,-26000.0,27.653846
Total Cash Flows From Investing Activities,16066000.0,-46446000.0,-45977000.0,-56274000.0,-1.285496
Dividends Paid,-13712000.0,-12769000.0,-12150000.0,-11561000.0,0.186057
Net Borrowings,432000.0,29014000.0,22057000.0,29305000.0,-0.985258
Total Cash Flows From Financing Activities,-87876000.0,-17974000.0,-20890000.0,-17716000.0,3.960262
Change In Cash and Cash Equivalents,5624000.0,-195000.0,-636000.0,7276000.0,-0.227048

In [35]:
portfolio = industry()

In [38]:
portfolio.statistics(T.stats_list)

In [39]:
portfolio.statistics.dropna(how='all')

,NFLX,AAPL,BCE.TO,T,CMCSA,Averages
% Held by Insiders 1,1.74,0.070000,NaN,0.070000,0.710000,0.647500
% Held by Institutions 1,77.15,60.950000,NaN,55.440000,84.670000,69.552500
200-Day Moving Average 3,343.95,198.400000,60.630000,32.790000,42.570000,135.668000
5 Year Average Dividend Yield 4,NaN,1.650000,4.840000,5.480000,1.690000,3.415000
50-Day Moving Average 3,299.83,209.230000,62.300000,35.440000,44.170000,130.194000
52 Week High 3,386.80,233.470000,64.500000,38.750000,47.270000,154.158000
52 Week Low 3,231.23,142.000000,50.720000,26.800000,32.610000,96.672000
52-Week Change 3,-20.20,1.250000,22.440000,9.930000,24.150000,7.514000
Adjusted Returns,NaN,1.277778,9.166667,7.302632,1.808081,4.888789
Avg Vol (10 day) 3,7.18,30.020000,2.310000,53.070000,14.210000,21.358000
Avg Vol (3 month) 3,7.12,26.340000,1.470000,31.890000,16.710000,16.706000
Beta (3Y Monthly),1.48,1.080000,0.540000,0.760000,0.990000,0.970000
Book Value Per Share (mrq),13.94,21.290000,17.920000,25.220000,16.910000,19.056000
Current Ratio (mrq),0.85,1.500000,0.570000,0.710000,0.690000,0.864000
Diluted EPS (ttm),2.54,11.780000,3.250000,2.370000,2.620000,4.512000
EBITDA,196.00,7654.000000,908.000000,5626.000000,3248.000000,3526.400000
Enterprise Value 3,13633.00,NaN,8847.000000,46931.000000,32282.000000,25423.250000
Enterprise Value/EBITDA 6,69.72,13.330000,9.740000,8.340000,9.940000,22.214000
Enterprise Value/Revenue 3,7.73,3.940000,3.720000,2.560000,3.110000,4.212000
Float,430.97,426.000000,899.450000,730.000000,450.000000,587.284000
Forward Annual Dividend Rate 4,NaN,3.080000,3.170000,2.040000,0.840000,2.282500
Forward Annual Dividend Yield 4,NaN,1.380000,4.950000,5.550000,1.790000,3.417500
Forward P/E 1,50.46,17.360000,17.170000,10.260000,13.690000,21.788000
Gross Profit (ttm),583.00,10184.000000,982.000000,9134.000000,6481.000000,5472.800000
Market Cap (intraday) 5,12548.00,99856.000000,5733.000000,27146.000000,21216.000000,33299.800000
Net Income Avi to Common (ttm),115.00,5569.000000,292.000000,1739.000000,1207.000000,1784.400000
Operating Cash Flow (ttm),-285.00,6900.000000,744.000000,4976.000000,2603.000000,2987.600000
Operating Margin (ttm),10.56,24.870000,23.410000,15.800000,19.350000,18.798000
PEG Ratio (5 yr expected) 1,1.89,1.970000,4.840000,3.040000,1.480000,2.644000
Payout Ratio 4,0.00,25.130000,95.230000,86.380000,30.530000,47.454000
Price/Book (mrq),20.55,10.380000,3.550000,1.470000,2.760000,7.742000
Price/Sales (ttm),7.12,3.850000,2.410000,1.480000,2.050000,3.382000
Profit Margin,6.53,21.500000,12.920000,9.470000,11.640000,12.412000
Quarterly Earnings Growth (yoy),-29.60,-12.800000,8.100000,-27.700000,-2.800000,-12.960000
Quarterly Revenue Growth (yoy),26.00,1.000000,2.500000,15.300000,23.600000,13.680000
Return on Assets (ttm),4.41,11.990000,5.950000,3.350000,5.600000,6.260000
Return on Equity (ttm),21.72,52.690000,15.140000,9.660000,16.170000,23.076000
Revenue (ttm),1763.00,25903.000000,2376.000000,18352.000000,10370.000000,11752.800000
Revenue Per Share (ttm),40.37,55.170000,26.440000,25.110000,22.810000,33.980000
S&P500 52-Week Change 3,2.59,2.590000,3.400000,2.590000,2.590000,2.752000
Shares Outstanding 5,437.84,452.000000,900.100000,731.000000,454.000000,594.988000
"Shares Short (Aug 15, 2019) 4",21.40,45.590000,NaN,102.020000,81.710000,62.680000
"Shares Short (Aug 30, 2019) 4",NaN,NaN,28.340000,NaN,NaN,28.340000
"Shares Short (prior month Jul 15, 2019) 4",18.35,42.430000,NaN,101.660000,74.730000,59.292500
"Shares Short (prior month Jul 31, 2019) 4",NaN,NaN,27.570000,NaN,NaN,27.570000
"Short % of Float (Aug 15, 2019) 4",5.02,0.960000,NaN,1.400000,1.820000,2.300000
"Short % of Shares Outstanding (Aug 15, 2019) 4",4.89,1.010000,NaN,1.400000,1.800000,2.275000
"Short % of Shares Outstanding (Aug 30, 2019) 4",NaN,NaN,3.150000,NaN,NaN,3.150000
"Short Ratio (Aug 15, 2019) 4",2.22,1.560000,NaN,3.160000,4.700000,2.910000
"Short Ratio (Aug 30, 2019) 4",NaN,NaN,22.000000,NaN,NaN,22.000000
Total Cash (mrq),500.00,9461.000000,109.000000,847.000000,392.000000,2261.800000
Total Cash Per Share (mrq),11.43,20.940000,1.220000,1.160000,0.860000,7.122000
Total Debt (mrq),1368.00,10842.000000,2763.000000,19936.000000,11227.000000,9227.200000
Total Debt/Equity (mrq),224.03,112.400000,135.010000,102.720000,141.830000,143.198000
Total Returns,-20.20,2.630000,27.390000,15.480000,25.940000,10.248000
Trailing Annual Dividend Rate 3,NaN,2.960000,3.100000,2.030000,0.800000,2.222500
Trailing Annual Dividend Yield 3,NaN,1.330000,4.870000,5.520000,1.700000,3.355000
Trailing P/E,112.83,18.760000,19.600000,15.670000,17.830000,36.938000

In [41]:
statistics_df = portfolio.statistics.dropna(how='all').T.sort_values("Diluted EPS (ttm)", ascending=False)[['Diluted EPS (ttm)', 'EBITDA', 'Beta (3Y Monthly)', 'Profit Margin','Trailing Annual Dividend Yield 3']]

In [42]:
statistics_df

,Diluted EPS (ttm),EBITDA,Beta (3Y Monthly),Profit Margin,Trailing Annual Dividend Yield 3
AAPL,11.780,7654.0,1.08,21.500,1.330
Averages,4.512,3526.4,0.97,12.412,3.355
BCE.TO,3.250,908.0,0.54,12.920,4.870
CMCSA,2.620,3248.0,0.99,11.640,1.700
NFLX,2.540,196.0,1.48,6.530,NaN
T,2.370,5626.0,0.76,9.470,5.520

In [44]:
portfolio.cashflow(AAPL.cash_list)

In [45]:
portfolio.cashflow.dropna(how='all')

,NFLX,AAPL,BCE.TO,T,CMCSA
Adjustments To Net Income,1.578814,-6.173548,-1.923077,-0.568348,-0.143387
Capital Expenditure,0.906299,0.183693,0.095146,0.061754,0.204142
Change In Cash and Cash Equivalents,0.421898,-0.227048,-1.361702,12.076393,-1.209288
Changes In Accounts Receivables,NaN,-13.762590,NaN,-42.466667,0.132768
Changes In Inventories,NaN,-4.478992,NaN,NaN,NaN
Changes In Liabilities,1.759394,0.511004,NaN,0.183161,-2.026042
Changes In Other Operating Activities,-1.970918,4.963690,0.580913,0.841546,0.108508
Depreciation,0.335148,-0.031447,0.117230,0.244744,0.269240
Dividends Paid,NaN,0.186057,0.219491,0.314706,0.375462
Effect Of Exchange Rate Changes,1.491962,NaN,NaN,NaN,-0.000000
Investments,NaN,-1.694441,NaN,-1.799353,0.603316
Net Borrowings,1.641235,-0.985258,-1.313725,-1.367326,28.253419
Net Income,8.876322,0.114938,0.093727,0.451480,0.437094
Other Cash Flows from Financing Activities,-1.607204,NaN,0.469388,0.028018,-0.315068
Other Cash flows from Investing Activities,65.207113,27.653846,-0.483871,250.000000,2.604545
Total Cash Flow From Operating Activities,2.576647,-0.047154,0.176921,0.215217,0.246959
Total Cash Flows From Financing Activities,1.468197,3.960262,0.513488,-3.656819,-3.970665
Total Cash Flows From Investing Activities,0.892495,-1.285496,0.066116,0.284897,3.250585

In [46]:
portfolio.balance_sheet(AAPL.bs_list)

In [47]:
portfolio.balance_sheet.dropna(how='all')

,NFLX,AAPL,BCE.TO,T,CMCSA,Averages
Accounts Payable,1.220927,0.574753,0.128673,0.283698,0.366693,0.514949
Capital Surplus,NaN,NaN,0.017391,0.398405,-0.027442,0.129451
Cash And Cash Equivalents,1.097176,0.226941,-0.306688,0.016208,0.661874,0.339102
Common Stock,0.748167,0.466334,0.106961,0.173364,0.862069,0.471379
Deferred Long Term Asset Charges,2.125744,NaN,0.258427,NaN,NaN,1.192086
Goodwill,NaN,NaN,0.272293,0.399759,1.008013,0.560022
Intangible Assets,2.468952,NaN,0.181550,0.357195,0.280605,0.822075
Inventory,NaN,0.684121,0.038462,-0.312918,NaN,0.136555
Long Term Debt,3.368822,0.757674,0.339416,0.369844,1.181879,1.203527
Long Term Investments,NaN,0.041045,-0.271852,3.425280,1.445099,1.159893
Minority Interest,NaN,NaN,0.065359,9.108359,-0.247440,2.975426
Net Receivables,NaN,0.614705,0.327019,0.593313,0.610209,0.536311
Net Tangible Assets,3.653121,-0.028991,0.148454,0.229039,0.619064,0.924138
Other Assets,2.163707,3.109738,1.241060,1.063078,0.678233,1.651163
Other Current Assets,0.890233,-0.177251,0.854111,0.639373,1.241993,0.689692
Other Current Liabilities,0.737042,2.677667,0.150380,0.547086,0.388309,0.900097
Other Liabilities,0.870740,0.294891,0.177963,-0.041443,-0.029070,0.254616
Other Stockholder Equity,-0.547843,9.011594,-0.243697,-0.203412,1.114943,1.826317
"Property, plant and equipment",1.412065,0.838102,0.148590,0.056432,0.319976,0.555033
Retained Earnings,2.123772,-0.237138,-0.222520,0.744914,0.960631,0.673932
Short Term Investments,NaN,0.971974,NaN,NaN,NaN,0.971974
Short/Current Long Term Debt,NaN,2.495424,-0.968833,-0.078092,0.198235,0.411684
Total Assets,1.545793,0.259622,0.189757,0.320837,0.510944,0.565391
Total Current Assets,0.784687,0.469478,0.204867,0.428845,0.775827,0.532741
Total Current Liabilities,0.837963,0.449770,0.043735,0.347248,0.518484,0.439440
Total Liabilities,1.598631,0.512240,0.187418,0.211259,0.597001,0.621310
Total stockholders' equity,1.356168,-0.102283,0.256548,0.500673,0.370086,0.476238
Treasury Stock,-0.547843,9.011594,-0.243697,0.076054,0.025224,1.664266

In [48]:
portfolio.financials(AAPL.fin_list)

In [49]:
portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)

,Total Revenue,Cost of Revenue,Gross Profit,Research Development,Selling General and Administrative,Others,Total Operating Expenses,Operating Income or Loss,Total Other Income/Expenses Net,Earnings Before Interest and Taxes,Interest Expense,Income Before Tax,Income Tax Expense,Minority Interest,Net Income From Continuing Ops,Net Income,Net Income Applicable To Common Shares
NFLX,1.329717,1.170879,1.663030,0.877438,1.436017,NaN,1.191814,4.248821,1.310392,4.248821,2.168367,7.644029,-0.209312,NaN,8.876322,8.876322,8.876322
Averages,0.397701,0.382620,0.452294,0.821079,0.374760,0.0,0.383381,0.954603,0.577584,0.954603,1.386172,1.615443,-0.209838,2.975426,1.989608,1.994712,1.996474
CMCSA,0.268380,0.316718,0.247402,NaN,0.275236,NaN,0.290334,0.188086,0.433740,0.188086,0.310881,0.139844,-0.318411,-0.247440,0.409961,0.437094,0.437094
T,0.163180,0.184545,0.145220,NaN,-0.038563,NaN,0.144171,0.254932,0.497890,0.254932,0.931311,0.202059,-0.297645,9.108359,0.457807,0.451480,0.451480
BCE.TO,0.090825,0.072018,0.118096,NaN,0.035294,0.0,0.092342,0.085839,0.085589,0.085839,0.100110,0.085933,0.076840,0.065359,0.089011,0.093727,0.102534
AAPL,0.136405,0.168943,0.087721,0.764720,0.165818,NaN,0.198246,-0.004661,0.560311,-0.004661,3.420191,0.005351,-0.300664,NaN,0.114938,0.114938,0.114938

In [50]:
GP = DataFrame(portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)['Gross Profit'])

In [51]:
Debt = portfolio.balance_sheet.dropna(how='all').T.sort_values('Long Term Debt', ascending=False)['Long Term Debt']

In [52]:
NI = portfolio.cashflow.dropna(how='all').T.sort_values("Net Income", ascending=False)['Net Income']

In [61]:
pandas.concat([statistics_df, NI, Debt, GP], axis=1, sort=True).sort_values('Diluted EPS (ttm)', ascending=False)

,Diluted EPS (ttm),EBITDA,Beta (3Y Monthly),Profit Margin,Trailing Annual Dividend Yield 3,Net Income,Long Term Debt,Gross Profit
AAPL,11.780,7654.0,1.08,21.500,1.330,0.114938,0.757674,0.087721
Averages,4.512,3526.4,0.97,12.412,3.355,NaN,1.203527,0.452294
BCE.TO,3.250,908.0,0.54,12.920,4.870,0.093727,0.339416,0.118096
CMCSA,2.620,3248.0,0.99,11.640,1.700,0.437094,1.181879,0.247402
NFLX,2.540,196.0,1.48,6.530,NaN,8.876322,3.368822,1.663030
T,2.370,5626.0,0.76,9.470,5.520,0.451480,0.369844,0.145220

In [55]:
cash_debt = AAPL.balance_sheet.T['Cash And Cash Equivalents'][0]/AAPL.balance_sheet.T['Long Term Debt'][0]

In [56]:
cash_debt*100

27.644956526377555

In [57]:
debt = AAPL.balance_sheet.T['Long Term Debt'][0]/AAPL.balance_sheet.T['Long Term Debt'][1]

In [58]:
debt

0.96428240764554

In [59]:
AAPL.balance_sheet.dropna(how='all')

Period Ending,9/29/2018,9/30/2017,9/24/2016,9/26/2015,Changes
AAPL,,,,,
Cash And Cash Equivalents,25913000.0,20289000.0,20484000.0,21120000.0,0.226941
Short Term Investments,40388000.0,53892000.0,46671000.0,20481000.0,0.971974
Net Receivables,48995000.0,35673000.0,29299000.0,30343000.0,0.614705
Inventory,3956000.0,4855000.0,2132000.0,2349000.0,0.684121
Other Current Assets,12087000.0,13936000.0,8283000.0,14691000.0,-0.177251
Total Current Assets,131339000.0,128645000.0,106869000.0,89378000.0,0.469478
Long Term Investments,170799000.0,194714000.0,170430000.0,164065000.0,0.041045
"Property, plant and equipment",41304000.0,33783000.0,27010000.0,22471000.0,0.838102
Goodwill,NaN,NaN,5414000.0,5116000.0,NaN
Intangible Assets,NaN,NaN,3206000.0,3893000.0,NaN
Other Assets,22283000.0,18177000.0,8757000.0,5422000.0,3.109738
Total Assets,365725000.0,375319000.0,321686000.0,290345000.0,0.259622
Accounts Payable,55888000.0,44242000.0,37294000.0,35490000.0,0.574753
Short/Current Long Term Debt,8784000.0,6496000.0,3500000.0,2513000.0,2.495424
Other Current Liabilities,40230000.0,38099000.0,8243000.0,10939000.0,2.677667
Total Current Liabilities,116866000.0,100814000.0,79006000.0,80610000.0,0.449770
Long Term Debt,93735000.0,97207000.0,75427000.0,53329000.0,0.757674
Other Liabilities,47977000.0,43251000.0,39004000.0,37051000.0,0.294891
Total Liabilities,258578000.0,241272000.0,193437000.0,170990000.0,0.512240
Common Stock,40201000.0,35867000.0,31251000.0,27416000.0,0.466334
Retained Earnings,70400000.0,98330000.0,96364000.0,92284000.0,-0.237138
Treasury Stock,-3454000.0,-150000.0,634000.0,-345000.0,9.011594
Other Stockholder Equity,-3454000.0,-150000.0,634000.0,-345000.0,9.011594
Total stockholders' equity,107147000.0,134047000.0,128249000.0,119355000.0,-0.102283
Net Tangible Assets,107147000.0,134047000.0,119629000.0,110346000.0,-0.028991

In [60]:
AAPL.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list'],
 ['financials', 'fin_list'],
 ['cashflow', 'cash_list'],
 ['earnings_est',
  'revenue',
  'earnings_history',
  'eps_trend',
  'eps_revisions',
  'growth_estimates',
  'a_list']]