In [1]:
from finance_python import stock, sector, industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
def print_mult(item):
    for each in item:
        print(each, '\n', '--------------')

In [3]:
energy = sector('energy')

In [4]:
symbols = ['EMH.V', 'FIRE.TO', 'FAF.TO', 'APHA.TO']

start = date.today() - timedelta(days=365)
end = date.today()

In [5]:
stock_loop = lambda x: stock(x, start, end)
stat = lambda x: stocks[x].stats()
bal = lambda x: stocks[x].balance()
fin = lambda x: stocks[x].financial()
ca = lambda x: stocks[x].cash()
an = lambda x: stocks[x].analyze()

In [6]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

85.58204817771912

In [7]:
timer_start = time.time()

for each in range(0, len(stocks)):
    stat(each)
    
timer_end = time.time()
print(timer_end - timer_start)

6.029880523681641

In [8]:
timer_start = time.time()

for each in range(0, len(stocks)):
    bal(each)
    
timer_end = time.time()
print(timer_end - timer_start)

6.573606967926025

In [9]:
timer_start = time.time()

for each in range(0, len(stocks)):
    fin(each)
    
timer_end = time.time()
print(timer_end - timer_start)

8.000604391098022

In [10]:
timer_start = time.time()

for each in range(0, len(stocks)):
    ca(each)
    
timer_end = time.time()
print(timer_end - timer_start)

4.633897066116333

In [11]:
timer_start = time.time()

for each in range(0, len(stocks)):
    an(each)
    
timer_end = time.time()
print(timer_end - timer_start)

10.588404655456543

In [12]:
EMH, FIRE, FAF, APHA = stocks

In [13]:
price = list(map(lambda symbol, x: {symbol: stocks[x].price}, symbols, range(0, len(symbols))))

In [14]:
price

[{'EMH.V': 1.64}, {'FIRE.TO': 1.38}, {'FAF.TO': 1.39}, {'APHA.TO': 8.15}]

In [15]:
WMD.description

NameError: name 'WMD' is not defined

In [18]:
FAF.statistics.dropna()

                                                  FAF.TO
Market Cap (intraday) 5                         152.9600
Enterprise Value 3                              190.3000
Forward P/E 1                                   139.0000
Price/Sales (ttm)                                 6.7900
Price/Book (mrq)                                  4.0600
Enterprise Value/Revenue 3                        8.4500
Enterprise Value/EBITDA 6                        -8.3100
S&P500 52-Week Change 3                           2.9900
52 Week High 3                                    1.6700
52 Week Low 3                                     1.0500
50-Day Moving Average 3                           1.4191
200-Day Moving Average 3                          1.4191
Avg Vol (3 month) 3                               3.5101
Avg Vol (10 day) 3                                6.6707
Shares Outstanding 5                            110.0400
Float                                            91.6300
Shares Short (Aug 30, 2019) 4                     8.6184
Short Ratio (Aug 30, 2019) 4                      0.9600
Short % of Shares Outstanding (Aug 30, 2019) 4    0.7800
Shares Short (prior month Jul 31, 2019) 4         1.6800
Profit Margin                                  -232.6500
Operating Margin (ttm)                         -106.4400
Revenue (ttm)                                    22.5200
Revenue Per Share (ttm)                           0.2800
Gross Profit (ttm)                                4.9800
EBITDA                                          -22.9000
Net Income Avi to Common (ttm)                  -52.3900
Diluted EPS (ttm)                                -0.6460
Total Cash (mrq)                                 25.3800
Total Cash Per Share (mrq)                        0.2200
Total Debt (mrq)                                 52.6300
Total Debt/Equity (mrq)                         148.1200
Current Ratio (mrq)                               1.8400
Book Value Per Share (mrq)                        0.3400
Operating Cash Flow (ttm)                       -20.6000

In [19]:
FAF.description

'Fire  Flower Holdings Corp., through its subsidiary, Fire  Flower Inc., operates as an independent retail chain that offers cannabis products and accessories to the adult-use market in Alberta and Saskatchewan. It also provides brand licensing and consulting services to licensed cannabis retail stores in Ontario. In addition, the company engages in the wholesale of regulated cannabis products and accessories in Saskatchewan; and operation of regulated cannabis e-commerce platform. It owns or has interests in 28 cannabis retail store licenses in the provinces of Alberta, Saskatchewan, Manitoba, Ontario, and the Yukon territory. The company is headquartered in Toronto, Canada.'

In [20]:
FAF.earnings_est

,Current Qtr. (Aug 2019),Next Qtr. (Nov 2019),Current Year (2020),Next Year (2021)
Earnings Estimate,,,,
No. of Analysts,0.0,0.0,1.00,1.00
Avg. Estimate,0.0,0.0,-0.05,0.01
Low Estimate,0.0,0.0,-0.05,0.01
High Estimate,0.0,0.0,-0.05,0.01
Year Ago EPS,NaN,NaN,NaN,-0.05

In [21]:
basic_df = lambda x: {'symbol': symbols[x], 'price': stocks[x].price, 'description': stocks[x].description, 'sector': stocks[x].sector}

In [22]:
dict = list(map(basic_df, range(0, len(stocks))))
df = DataFrame(dict)
df.sort_values('sector')

,description,price,sector,symbol
0,"Emerald Health Therapeutics, Inc., together wi...",1.64,Drug Manufacturers - Specialty Generic,EMH.V
1,"The Supreme Cannabis Company, Inc. engages in ...",1.38,Drug Manufacturers - Specialty Generic,FIRE.TO
3,Aphria Inc. produces and sells medical cannabi...,8.15,Drug Manufacturers - Specialty Generic,APHA.TO
2,"Fire Flower Holdings Corp., through its subsi...",1.39,Pharmaceutical Retailers,FAF.TO

In [23]:
EMH.dividends

[                                                Date  Dividends
 0  *Close price adjusted for splits.**Adjusted cl...        NaN]

In [24]:
APHA.dividends

[                                                Date  Dividends
 0  *Close price adjusted for splits.**Adjusted cl...        NaN]

In [25]:
portfolio = industry()

In [26]:
portfolio.statistics(APHA.stats_list)

In [27]:
portfolio.statistics.dropna(how='all')

,EMH.V,FIRE.TO,FAF.TO,APHA.TO,Averages
200-Day Moving Average 3,2.9590,1.7129,1.4191,9.79,3.970250
50-Day Moving Average 3,1.8788,1.4027,1.4191,8.64,3.335150
52 Week High 3,5.2500,2.4300,1.6700,20.96,7.577500
52 Week Low 3,1.5650,1.1500,1.0500,4.76,2.131250
52-Week Change 3,-68.0000,-38.2200,NaN,-59.64,-55.286667
Avg Vol (10 day) 3,2.8038,7.3657,6.6707,1.53,4.592550
Avg Vol (3 month) 3,4.0425,6.5548,3.5101,1.89,3.999350
Beta (3Y Monthly),2.2800,4.2300,NaN,3.70,3.403333
Book Value Per Share (mrq),1.3300,0.7000,0.3400,6.79,2.290000
Current Ratio (mrq),0.9200,3.4100,1.8400,5.64,2.952500
Diluted EPS (ttm),-0.1580,-0.0520,-0.6460,-0.07,-0.231500
EBITDA,-44.6300,4.1800,-22.9000,-41.08,-26.107500
Enterprise Value 3,259.8000,512.8100,190.3000,199.00,290.477500
Enterprise Value/EBITDA 6,-5.8200,122.5900,-8.3100,-48.49,14.992500
Enterprise Value/Revenue 3,32.3100,12.2600,8.4500,8.40,15.355000
Float,110.6100,347.8800,91.6300,250.74,200.215000
Forward P/E 1,-9.1100,12.5500,139.0000,25.47,41.977500
Gross Profit (ttm),-2.7021,36.8500,4.9800,75.42,28.636975
Levered Free Cash Flow (ttm),-55.0600,-114.0900,NaN,-230.63,-133.260000
Market Cap (intraday) 5,245.0900,459.9900,152.9600,205.00,265.760000
Net Income Avi to Common (ttm),-23.9600,-14.5000,-52.3900,-16.50,-26.837500
Operating Cash Flow (ttm),-38.0000,-14.8400,-20.6000,-55.60,-32.260000
Operating Margin (ttm),-613.0000,-4.4500,-106.4400,-26.93,-187.705000
PEG Ratio (5 yr expected) 1,NaN,1.3500,NaN,NaN,1.350000
Payout Ratio 4,0.0000,0.0000,NaN,0.00,0.000000
Price/Book (mrq),1.2400,1.9700,4.0600,1.20,2.117500
Price/Sales (ttm),30.4800,11.0000,6.7900,8.63,14.225000
Profit Margin,-298.0700,-34.6500,-232.6500,-6.96,-143.082500
Quarterly Revenue Growth (yoy),NaN,436.1000,NaN,969.10,702.600000
Return on Assets (ttm),-13.3500,-0.4400,NaN,-2.13,-5.306667
Return on Equity (ttm),-12.8300,-8.1400,NaN,-1.14,-7.370000
Revenue (ttm),8.0400,41.8300,22.5200,237.11,77.375000
Revenue Per Share (ttm),0.0500,0.1500,0.2800,0.98,0.365000
S&P500 52-Week Change 3,2.9900,2.9900,2.9900,2.99,2.990000
Shares Outstanding 5,149.4400,333.3200,110.0400,250.99,210.947500
"Shares Short (Aug 30, 2019) 4",2.5800,1.1300,8.6184,4.28,4.152100
"Shares Short (prior month Jul 31, 2019) 4",2.4300,1.2600,1.6800,5.84,2.802500
"Short % of Shares Outstanding (Aug 30, 2019) 4",2.3200,0.3400,0.7800,1.71,1.287500
"Short Ratio (Aug 30, 2019) 4",6.3300,1.3600,0.9600,1.54,2.547500
Total Cash (mrq),2.6100,54.8200,25.3800,571.00,163.452500
Total Cash Per Share (mrq),0.0200,0.1600,0.2200,2.28,0.670000
Total Debt (mrq),9.7100,79.0500,52.6300,488.59,157.495000
Total Debt/Equity (mrq),4.7900,37.4700,148.1200,28.19,54.642500
Total Returns,-68.0000,-38.2200,NaN,-59.64,-55.286667

In [28]:
statistics_df = portfolio.statistics.dropna(how='all').T.sort_values("Diluted EPS (ttm)", ascending=False)[['Diluted EPS (ttm)', 'Beta (3Y Monthly)', 'Profit Margin']]

In [29]:
statistics_df

          Diluted EPS (ttm)  Beta (3Y Monthly)  Profit Margin
FIRE.TO             -0.0520           4.230000       -34.6500
APHA.TO             -0.0700           3.700000        -6.9600
EMH.V               -0.1580           2.280000      -298.0700
Averages            -0.2315           3.403333      -143.0825
FAF.TO              -0.6460                NaN      -232.6500

In [31]:
portfolio.cashflow(APHA.cash_list)

In [32]:
portfolio.cashflow.dropna(how='all')

,EMH.V,FIRE.TO,FAF.TO,APHA.TO
Adjustments To Net Income,-1.847288,1.545866,27.946939,53.791837
Capital Expenditure,57.343578,62.091480,13.582421,45.534626
Change In Cash and Cash Equivalents,4.180982,-1.339831,0.447920,51.125334
Changes In Accounts Receivables,-7834.941176,45.693482,3.050453,-8.004074
Changes In Inventories,120.451245,5.183486,-0.000000,27.457530
Changes In Liabilities,62.366538,31.189138,17.523346,1.164319
Changes In Other Operating Activities,-18.298438,-25.945958,5.231380,-19.144726
Depreciation,74.333875,28.473879,1840.940711,24.364816
Investments,0.031576,NaN,NaN,-41.078836
Net Borrowings,-1.098623,0.941633,20.077932,13.631397
Net Income,7.743072,2.304697,16.551993,-42.458836
Other Cash Flows from Financing Activities,-179.310424,NaN,49.495513,NaN
Other Cash flows from Investing Activities,9.183766,NaN,NaN,-338.806985
Total Cash Flow From Operating Activities,11.911015,5.741720,8.046142,55.272732
Total Cash Flows From Financing Activities,88.501705,12.430227,4.675065,43.234170
Total Cash Flows From Investing Activities,199.102106,33.532118,14.946487,28.791582

In [33]:
portfolio.balance_sheet(APHA.bs_list)

In [34]:
portfolio.statistics.dropna(how='all')

,EMH.V,FIRE.TO,FAF.TO,APHA.TO,Averages
200-Day Moving Average 3,2.9590,1.7129,1.4191,9.79,3.970250
50-Day Moving Average 3,1.8788,1.4027,1.4191,8.64,3.335150
52 Week High 3,5.2500,2.4300,1.6700,20.96,7.577500
52 Week Low 3,1.5650,1.1500,1.0500,4.76,2.131250
52-Week Change 3,-68.0000,-38.2200,NaN,-59.64,-55.286667
Avg Vol (10 day) 3,2.8038,7.3657,6.6707,1.53,4.592550
Avg Vol (3 month) 3,4.0425,6.5548,3.5101,1.89,3.999350
Beta (3Y Monthly),2.2800,4.2300,NaN,3.70,3.403333
Book Value Per Share (mrq),1.3300,0.7000,0.3400,6.79,2.290000
Current Ratio (mrq),0.9200,3.4100,1.8400,5.64,2.952500
Diluted EPS (ttm),-0.1580,-0.0520,-0.6460,-0.07,-0.231500
EBITDA,-44.6300,4.1800,-22.9000,-41.08,-26.107500
Enterprise Value 3,259.8000,512.8100,190.3000,199.00,290.477500
Enterprise Value/EBITDA 6,-5.8200,122.5900,-8.3100,-48.49,14.992500
Enterprise Value/Revenue 3,32.3100,12.2600,8.4500,8.40,15.355000
Float,110.6100,347.8800,91.6300,250.74,200.215000
Forward P/E 1,-9.1100,12.5500,139.0000,25.47,41.977500
Gross Profit (ttm),-2.7021,36.8500,4.9800,75.42,28.636975
Levered Free Cash Flow (ttm),-55.0600,-114.0900,NaN,-230.63,-133.260000
Market Cap (intraday) 5,245.0900,459.9900,152.9600,205.00,265.760000
Net Income Avi to Common (ttm),-23.9600,-14.5000,-52.3900,-16.50,-26.837500
Operating Cash Flow (ttm),-38.0000,-14.8400,-20.6000,-55.60,-32.260000
Operating Margin (ttm),-613.0000,-4.4500,-106.4400,-26.93,-187.705000
PEG Ratio (5 yr expected) 1,NaN,1.3500,NaN,NaN,1.350000
Payout Ratio 4,0.0000,0.0000,NaN,0.00,0.000000
Price/Book (mrq),1.2400,1.9700,4.0600,1.20,2.117500
Price/Sales (ttm),30.4800,11.0000,6.7900,8.63,14.225000
Profit Margin,-298.0700,-34.6500,-232.6500,-6.96,-143.082500
Quarterly Revenue Growth (yoy),NaN,436.1000,NaN,969.10,702.600000
Return on Assets (ttm),-13.3500,-0.4400,NaN,-2.13,-5.306667
Return on Equity (ttm),-12.8300,-8.1400,NaN,-1.14,-7.370000
Revenue (ttm),8.0400,41.8300,22.5200,237.11,77.375000
Revenue Per Share (ttm),0.0500,0.1500,0.2800,0.98,0.365000
S&P500 52-Week Change 3,2.9900,2.9900,2.9900,2.99,2.990000
Shares Outstanding 5,149.4400,333.3200,110.0400,250.99,210.947500
"Shares Short (Aug 30, 2019) 4",2.5800,1.1300,8.6184,4.28,4.152100
"Shares Short (prior month Jul 31, 2019) 4",2.4300,1.2600,1.6800,5.84,2.802500
"Short % of Shares Outstanding (Aug 30, 2019) 4",2.3200,0.3400,0.7800,1.71,1.287500
"Short Ratio (Aug 30, 2019) 4",6.3300,1.3600,0.9600,1.54,2.547500
Total Cash (mrq),2.6100,54.8200,25.3800,571.00,163.452500
Total Cash Per Share (mrq),0.0200,0.1600,0.2200,2.28,0.670000
Total Debt (mrq),9.7100,79.0500,52.6300,488.59,157.495000
Total Debt/Equity (mrq),4.7900,37.4700,148.1200,28.19,54.642500
Total Returns,-68.0000,-38.2200,NaN,-59.64,-55.286667

In [35]:
portfolio.financials(APHA.fin_list)

In [36]:
portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)

,Total Revenue,Cost of Revenue,Gross Profit,Research Development,Selling General and Administrative,Total Operating Expenses,Operating Income or Loss,Total Other Income/Expenses Net,Earnings Before Interest and Taxes,Interest Expense,Income Before Tax,Income Tax Expense,Minority Interest,Net Income From Continuing Ops,Net Income,Net Income Applicable To Common Shares
APHA.TO,27.113825,85.646060,10.483374,5.311023,18.087969,30.598945,57.548898,166.042013,57.548898,19.090439,18.506533,-1.711667,1.965449,-42.458836,-42.458836,-42.458836
Averages,44.190801,47.766134,5.524855,4.624002,13.254476,16.214072,18.887948,282.297304,18.887948,70.998319,11.168723,-1.711667,1.965449,-3.935709,-3.964769,-3.964769
EMH.V,61.267777,9.886208,0.566335,3.936981,12.114529,10.162283,9.703924,-752.480730,9.703924,24.921973,7.866061,NaN,NaN,7.859310,7.743072,7.743072
FIRE.TO,NaN,NaN,NaN,NaN,10.761650,9.173082,-0.566934,110.135312,-0.566934,55.466104,1.750304,NaN,NaN,2.304697,2.304697,2.304697
FAF.TO,NaN,NaN,NaN,NaN,12.053755,14.921977,8.865904,1605.492621,8.865904,184.514759,16.551993,NaN,NaN,16.551993,16.551993,16.551993

In [37]:
GP = DataFrame(portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)['Gross Profit'])

In [38]:
Debt = portfolio.balance_sheet.dropna(how='all').T.sort_values('Long Term Debt', ascending=False)['Long Term Debt']

In [39]:
NI = portfolio.cashflow.dropna(how='all').T.sort_values("Net Income", ascending=False)['Net Income']

In [40]:
pandas.concat([statistics_df, NI, Debt, GP], axis=1, sort=True).sort_values('Diluted EPS (ttm)', ascending=False)

,Diluted EPS (ttm),Beta (3Y Monthly),Profit Margin,Net Income,Long Term Debt,Gross Profit
FIRE.TO,-0.0520,4.230000,-34.6500,2.304697,146.296441,NaN
APHA.TO,-0.0700,3.700000,-6.9600,-42.458836,NaN,10.483374
EMH.V,-0.1580,2.280000,-298.0700,7.743072,NaN,0.566335
Averages,-0.2315,3.403333,-143.0825,NaN,146.296441,5.524855
FAF.TO,-0.6460,NaN,-232.6500,16.551993,NaN,NaN

In [42]:
cash_debt = APHA.statistics.T['Total Cash (mrq)'][0]/APHA.statistics.T['Total Debt (mrq)'][0]

In [43]:
cash_debt*100

116.86690272007205

In [44]:
cash_debt = FAF.statistics.T['Total Cash (mrq)'][0]/FAF.statistics.T['Total Debt (mrq)'][0]

In [45]:
cash_debt*100

48.223446703401095

In [47]:
EMH.statistics.dropna()

                                                   EMH.V
Market Cap (intraday) 5                         245.0900
Enterprise Value 3                              259.8000
Forward P/E 1                                    -9.1100
Price/Sales (ttm)                                30.4800
Price/Book (mrq)                                  1.2400
Enterprise Value/Revenue 3                       32.3100
Enterprise Value/EBITDA 6                        -5.8200
Beta (3Y Monthly)                                 2.2800
52-Week Change 3                                -68.0000
S&P500 52-Week Change 3                           2.9900
52 Week High 3                                    5.2500
52 Week Low 3                                     1.5650
50-Day Moving Average 3                           1.8788
200-Day Moving Average 3                          2.9590
Avg Vol (3 month) 3                               4.0425
Avg Vol (10 day) 3                                2.8038
Shares Outstanding 5                            149.4400
Float                                           110.6100
Shares Short (Aug 30, 2019) 4                     2.5800
Short Ratio (Aug 30, 2019) 4                      6.3300
Short % of Shares Outstanding (Aug 30, 2019) 4    2.3200
Shares Short (prior month Jul 31, 2019) 4         2.4300
Payout Ratio 4                                    0.0000
Profit Margin                                  -298.0700
Operating Margin (ttm)                         -613.0000
Return on Assets (ttm)                          -13.3500
Return on Equity (ttm)                          -12.8300
Revenue (ttm)                                     8.0400
Revenue Per Share (ttm)                           0.0500
Gross Profit (ttm)                               -2.7021
EBITDA                                          -44.6300
Net Income Avi to Common (ttm)                  -23.9600
Diluted EPS (ttm)                                -0.1580
Total Cash (mrq)                                  2.6100
Total Cash Per Share (mrq)                        0.0200
Total Debt (mrq)                                  9.7100
Total Debt/Equity (mrq)                           4.7900
Current Ratio (mrq)                               0.9200
Book Value Per Share (mrq)                        1.3300
Operating Cash Flow (ttm)                       -38.0000
Levered Free Cash Flow (ttm)                    -55.0600
Total Returns                                   -68.0000

In [48]:
change = FIRE.financials.T['Gross Profit'][0] - FIRE.financials.T['Gross Profit'][-3]

In [49]:
change*100/FIRE.financials.T['Gross Profit'][-3]

7919.907773127989

In [50]:
change = FAF.financials.T['Gross Profit'][0] -FAF.financials.T['Gross Profit'][-3]

In [51]:
x = change/FAF.financials.T['Gross Profit'][-3]

In [53]:
x

0.0

In [52]:
FAF.financials.T['Gross Profit']

Period Ending
2/2/2019    4977.498
2/3/2018         NaN
Changes          NaN
Name: Gross Profit, dtype: float64

In [54]:
change/FAF.financials.T['Gross Profit'][-3]

0.0

In [55]:
change = APHA.financials.T['Gross Profit'][0] - APHA.financials.T['Gross Profit'][-3]

In [56]:
change*100/APHA.financials.T['Gross Profit'][-3]

336.035150604151

In [62]:
EMH.financials.T['Gross Profit']

Period Ending
12/31/2018   -270.210000
12/31/2017   -285.517000
12/31/2016   -349.946000
12/31/2015   -172.511000
Changes         0.566335
Name: Gross Profit, dtype: float64

In [63]:
EMH.financials.T['Gross Profit'][-3]

-349.946

In [64]:
EMH.financials.T['Gross Profit'][0]

-270.21

In [65]:
change*100/EMH.financials.T['Gross Profit'][-3]

-16609.41973904545

In [66]:
EMH.description

'Emerald Health Therapeutics, Inc., together with its subsidiaries, produces and sells medical cannabis in Canada. It is also involved in developing natural health products. The company was formerly known as T-Bird Pharma Inc. and changed its name to Emerald Health Therapeutics, Inc. in June 2015. Emerald Health Therapeutics, Inc. is headquartered in Vancouver, Canada.'

In [67]:
EMH.financials

Period Ending,12/31/2018,12/31/2017,12/31/2016,12/31/2015,Changes
EMH.V,,,,,
Total Revenue,1948.421,937.654,253.321,31.291,61.267777
Cost of Revenue,2218.631,1223.171,603.267,203.802,9.886208
Gross Profit,-270.210,-285.517,-349.946,-172.511,0.566335
Operating Expenses,NaN,NaN,NaN,NaN,NaN
Research Development,801.351,207.500,301.526,162.316,3.936981
Selling General and Administrative,25326.792,5498.988,1452.215,1931.201,12.114529
Non Recurring,NaN,NaN,NaN,NaN,NaN
Others,NaN,NaN,NaN,NaN,NaN
Total Operating Expenses,39292.677,10034.604,3154.144,3520.129,10.162283
Operating Income or Loss,-37344.256,-9096.950,-2900.823,-3488.838,9.703924
Income from Continuing Operations,NaN,NaN,NaN,NaN,NaN
Total Other Income/Expenses Net,6337.237,255.126,-39.678,-8.433,-752.480730
Earnings Before Interest and Taxes,-37344.256,-9096.950,-2900.823,-3488.838,9.703924
Interest Expense,-218.600,-218.600,-39.678,-8.433,24.921973
Income Before Tax,-31007.019,-8841.824,-2940.501,-3497.271,7.866061
Income Tax Expense,-23.611,NaN,NaN,NaN,NaN
Minority Interest,NaN,1956.834,1956.834,1956.834,NaN
Net Income From Continuing Ops,-30983.408,-8841.824,-2940.501,-3497.271,7.859310
Non-recurring Events,NaN,NaN,NaN,NaN,NaN
Discontinued Operations,NaN,NaN,NaN,NaN,NaN
Extraordinary Items,NaN,NaN,NaN,NaN,NaN
Effect Of Accounting Changes,NaN,NaN,NaN,NaN,NaN
Other Items,NaN,NaN,NaN,NaN,NaN
Net Income,-30576.893,-8731.832,-2940.501,-3497.271,7.743072
Preferred Stock And Other Adjustments,NaN,NaN,NaN,NaN,NaN
Net Income Applicable To Common Shares,-30576.893,-8731.832,-2940.501,-3497.271,7.743072