In [1]:
from finance_python import stock, sector, industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
def print_mult(item):
    for each in item:
        print(each, '\n', '--------------')

In [3]:
energy = sector('energy')

In [13]:
energy.symbol_lookup('MX')

[]

In [4]:
symbols = ['MX.TO', 'NTR.TO']

start = date.today() - timedelta(days=365)
end = date.today()

In [5]:
stock_loop = lambda x: stock(x, start, end)
stat = lambda x: stocks[x].stats()
bal = lambda x: stocks[x].balance()
fin = lambda x: stocks[x].financial()
ca = lambda x: stocks[x].cash()
an = lambda x: stocks[x].analyze()

In [6]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

13.138531684875488

In [7]:
timer_start = time.time()

for each in range(0, len(stocks)):
    stat(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.2232794761657715

In [8]:
timer_start = time.time()

for each in range(0, len(stocks)):
    bal(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.124725580215454

In [9]:
timer_start = time.time()

for each in range(0, len(stocks)):
    fin(each)
    
timer_end = time.time()
print(timer_end - timer_start)

1.9641659259796143

In [10]:
timer_start = time.time()

for each in range(0, len(stocks)):
    ca(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.4759204387664795

In [11]:
timer_start = time.time()

for each in range(0, len(stocks)):
    an(each)
    
timer_end = time.time()
print(timer_end - timer_start)

5.13134241104126

In [14]:
MX, NTR = stocks

In [15]:
MX.sector

'Chemicals'

In [16]:
NTR.sector

'Agricultural Inputs'

In [17]:
price = list(map(lambda symbol, x: {symbol: stocks[x].price}, symbols, range(0, len(symbols))))

In [18]:
price

[{'MX.TO': 48.06}, {'NTR.TO': 68.66}]

In [21]:
NTR.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,15.00,15.00,19.00,19.00
Avg. Estimate,0.45,0.60,2.83,3.43
Low Estimate,0.35,0.52,2.71,3.07
High Estimate,0.53,0.69,2.94,3.96
Year Ago EPS,0.47,0.54,2.69,2.83

In [48]:
NTR.statistics.dropna(how='all')

                                                     NTR.TO
Market Cap (intraday) 5                         3942.000000
Enterprise Value 3                              5037.000000
Trailing P/E                                      13.560000
Forward P/E 1                                     20.060000
PEG Ratio (5 yr expected) 1                        1.750000
Price/Sales (ttm)                                  2.040000
Price/Book (mrq)                                   1.700000
Enterprise Value/Revenue 3                         2.600000
Enterprise Value/EBITDA 6                         12.130000
Beta (3Y Monthly)                                  1.270000
52-Week Change 3                                  -8.910000
S&P500 52-Week Change 3                            4.110000
52 Week High 3                                    76.170000
52 Week Low 3                                     59.970000
50-Day Moving Average 3                           67.360000
200-Day Moving Average 3                          69.120000
Avg Vol (3 month) 3                                1.160000
Avg Vol (10 day) 3                                 1.170000
Shares Outstanding 5                             572.870000
Float                                            572.560000
Shares Short (Aug 30, 2019) 4                      3.070000
Short Ratio (Aug 30, 2019) 4                       2.530000
Short % of Shares Outstanding (Aug 30, 2019) 4     0.490000
Shares Short (prior month Jul 31, 2019) 4          2.920000
Forward Annual Dividend Rate 4                     2.370000
Forward Annual Dividend Yield 4                    3.450000
Trailing Annual Dividend Rate 3                    1.690000
Trailing Annual Dividend Yield 3                   2.460000
5 Year Average Dividend Yield 4                    4.290000
Payout Ratio 4                                   545.160000
Profit Margin                                     15.800000
Operating Margin (ttm)                            12.510000
Return on Assets (ttm)                             3.260000
Return on Equity (ttm)                             0.550000
Revenue (ttm)                                   1935.000000
Revenue Per Share (ttm)                           32.110000
Quarterly Revenue Growth (yoy)                     6.500000
Gross Profit (ttm)                               539.000000
EBITDA                                           415.000000
Net Income Avi to Common (ttm)                   128.000000
Diluted EPS (ttm)                                  5.070000
Quarterly Earnings Growth (yoy)                  -39.400000
Total Cash (mrq)                                 616.000000
Total Cash Per Share (mrq)                         1.080000
Total Debt (mrq)                                1165.000000
Total Debt/Equity (mrq)                           50.100000
Current Ratio (mrq)                                1.350000
Book Value Per Share (mrq)                        40.590000
Operating Cash Flow (ttm)                        245.000000
Adjusted Returns                                   2.716535
Total Returns                                     -5.460000

In [23]:
basic_df = lambda x: {'symbol': symbols[x], 'price': stocks[x].price, 'description': stocks[x].description, 'sector': stocks[x].sector}

In [24]:
dict = list(map(basic_df, range(0, len(stocks))))
df = DataFrame(dict)
df.sort_values('sector')

,description,price,sector,symbol
1,Nutrien Ltd. produces and markets crop nutrien...,68.66,Agricultural Inputs,NTR.TO
0,Methanex Corporation produces and supplies met...,48.06,Chemicals,MX.TO

In [26]:
MX.balance_sheet.dropna(how='all')

Period Ending,12/31/2018,12/31/2017,12/31/2016,12/31/2015,Changes
MX.TO,,,,,
Cash And Cash Equivalents,256077.0,375479.0,223890.0,254934.0,0.004484
Net Receivables,514568.0,536636.0,499603.0,504350.0,0.020260
Inventory,387959.0,304464.0,281328.0,253234.0,0.532018
Other Current Assets,60931.0,NaN,NaN,NaN,NaN
Total Current Assets,1252076.0,1243127.0,1025667.0,1032078.0,0.213160
Long Term Investments,202441.0,193424.0,201904.0,228667.0,-0.114691
"Property, plant and equipment",3025095.0,2998326.0,3117469.0,3158782.0,-0.042322
Other Assets,129387.0,175865.0,211623.0,136397.0,-0.051394
Deferred Long Term Asset Charges,59532.0,102341.0,137341.0,61881.0,-0.037960
Total Assets,4608999.0,4610742.0,4556663.0,4555924.0,0.011650
Accounts Payable,617414.0,626817.0,523216.0,508639.0,0.213855
Short/Current Long Term Debt,383793.0,55905.0,53997.0,47864.0,7.018406
Other Current Liabilities,36914.0,65226.0,29720.0,25439.0,0.451079
Total Current Liabilities,1047353.0,747948.0,606933.0,581942.0,0.799755
Long Term Debt,1074493.0,1446366.0,1502209.0,1488026.0,-0.277907
Other Liabilities,490170.0,671317.0,642171.0,517383.0,-0.052597
Minority Interest,296628.0,244347.0,208515.0,248844.0,0.192024
Total Liabilities,2801158.0,2865631.0,2751313.0,2587351.0,0.082635
Common Stock,446544.0,480331.0,511465.0,509464.0,-0.123502
Retained Earnings,1145476.0,1088150.0,1124104.0,1235615.0,-0.072951
Treasury Stock,-82404.0,-69841.0,-41302.0,-27776.0,1.966734
Capital Surplus,1597.0,2124.0,2568.0,2426.0,-0.341715
Other Stockholder Equity,-82404.0,-69841.0,-41302.0,-27776.0,1.966734
Total stockholders' equity,1511213.0,1500764.0,1596835.0,1719729.0,-0.121249
Net Tangible Assets,1511213.0,1500764.0,1596835.0,1719729.0,-0.121249

In [27]:
MX.statistics.dropna()

                                                     MX.TO
Market Cap (intraday) 5                         392.000000
Enterprise Value 3                              580.000000
Trailing P/E                                     11.060000
Price/Sales (ttm)                                 1.120000
Price/Book (mrq)                                  2.710000
Enterprise Value/Revenue 3                        1.660000
Enterprise Value/EBITDA 6                         6.870000
Beta (3Y Monthly)                                 1.930000
52-Week Change 3                                -51.750000
S&P500 52-Week Change 3                           4.110000
52 Week High 3                                  107.070000
52 Week Low 3                                    40.110000
50-Day Moving Average 3                          44.730000
200-Day Moving Average 3                         61.790000
Avg Vol (3 month) 3                               2.836900
Avg Vol (10 day) 3                                3.612500
Shares Outstanding 5                             76.000000
Float                                            75.560000
Shares Short (Aug 30, 2019) 4                     3.856400
Short Ratio (Aug 30, 2019) 4                      1.270000
Short % of Shares Outstanding (Aug 30, 2019) 4    0.510000
Shares Short (prior month Jul 31, 2019) 4         3.531900
Forward Annual Dividend Rate 4                    1.880000
Forward Annual Dividend Yield 4                   3.910000
Trailing Annual Dividend Rate 3                   1.350000
Trailing Annual Dividend Yield 3                  2.810000
5 Year Average Dividend Yield 4                   2.450000
Payout Ratio 4                                   29.160000
Profit Margin                                    10.800000
Operating Margin (ttm)                           15.750000
Return on Assets (ttm)                            7.170000
Return on Equity (ttm)                           24.140000
Revenue (ttm)                                   350.000000
Revenue Per Share (ttm)                          45.020000
Quarterly Revenue Growth (yoy)                  -22.700000
Gross Profit (ttm)                              107.000000
EBITDA                                          844.890000
Net Income Avi to Common (ttm)                  377.630000
Diluted EPS (ttm)                                 4.660000
Quarterly Earnings Growth (yoy)                 -54.900000
Total Cash (mrq)                                227.970000
Total Cash Per Share (mrq)                        2.990000
Total Debt (mrq)                                208.000000
Total Debt/Equity (mrq)                         119.500000
Current Ratio (mrq)                               1.040000
Book Value Per Share (mrq)                       19.010000
Operating Cash Flow (ttm)                       775.820000
Levered Free Cash Flow (ttm)                    176.690000
Adjusted Returns                                  2.025907
Total Returns                                   -47.840000

In [49]:
NTR.dividends

[                                                Date      Dividends
 0                                       Jun 27, 2019  0.43 Dividend
 1                                       Mar 28, 2019  0.43 Dividend
 2                                       Dec 28, 2018  0.43 Dividend
 3                                       Sep 27, 2018   0.4 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...            NaN]

In [29]:
MX.cashflow.dropna()

Period Ending,12/31/2018,12/31/2017,12/31/2016,12/31/2015,Changes
MX.TO,,,,,
Net Income,568982.0,316135.0,-12545.0,200617.0,1.836160
Depreciation,245303.0,232225.0,228054.0,194849.0,0.258939
Adjustments To Net Income,159923.0,281228.0,98802.0,18611.0,7.592929
Changes In Other Operating Activities,5998.0,-49368.0,-87644.0,-117126.0,-1.051210
Total Cash Flow From Operating Activities,980206.0,780220.0,226667.0,296951.0,2.300901
Capital Expenditure,-244476.0,-103170.0,-99881.0,-425021.0,-0.424791
Other Cash flows from Investing Activities,-61875.0,-2347.0,11672.0,-66234.0,-0.065812
Total Cash Flows From Investing Activities,-306351.0,-105517.0,-88209.0,-426255.0,-0.281296
Dividends Paid,-105676.0,-101497.0,-98797.0,-97221.0,0.086967
Net Borrowings,-55915.0,-63877.0,12139.0,-193480.0,-0.711004
Other Cash Flows from Financing Activities,-190462.0,-74679.0,-84350.0,-134305.0,0.418130
Total Cash Flows From Financing Activities,-793257.0,-523114.0,-169502.0,-567362.0,0.398150
Change In Cash and Cash Equivalents,-119402.0,151589.0,-31044.0,-696666.0,-0.828609

In [30]:
portfolio = industry()

In [31]:
portfolio.statistics(MX.stats_list)

In [32]:
portfolio.statistics.dropna(how='all')

,MX.TO,NTR.TO,Averages
200-Day Moving Average 3,61.790000,69.120000,65.455000
5 Year Average Dividend Yield 4,2.450000,4.290000,3.370000
50-Day Moving Average 3,44.730000,67.360000,56.045000
52 Week High 3,107.070000,76.170000,91.620000
52 Week Low 3,40.110000,59.970000,50.040000
52-Week Change 3,-51.750000,-8.910000,-30.330000
Adjusted Returns,2.025907,2.716535,2.371221
Avg Vol (10 day) 3,3.612500,1.170000,2.391250
Avg Vol (3 month) 3,2.836900,1.160000,1.998450
Beta (3Y Monthly),1.930000,1.270000,1.600000
Book Value Per Share (mrq),19.010000,40.590000,29.800000
Current Ratio (mrq),1.040000,1.350000,1.195000
Diluted EPS (ttm),4.660000,5.070000,4.865000
EBITDA,844.890000,415.000000,629.945000
Enterprise Value 3,580.000000,5037.000000,2808.500000
Enterprise Value/EBITDA 6,6.870000,12.130000,9.500000
Enterprise Value/Revenue 3,1.660000,2.600000,2.130000
Float,75.560000,572.560000,324.060000
Forward Annual Dividend Rate 4,1.880000,2.370000,2.125000
Forward Annual Dividend Yield 4,3.910000,3.450000,3.680000
Forward P/E 1,NaN,20.060000,20.060000
Gross Profit (ttm),107.000000,539.000000,323.000000
Levered Free Cash Flow (ttm),176.690000,NaN,176.690000
Market Cap (intraday) 5,392.000000,3942.000000,2167.000000
Net Income Avi to Common (ttm),377.630000,128.000000,252.815000
Operating Cash Flow (ttm),775.820000,245.000000,510.410000
Operating Margin (ttm),15.750000,12.510000,14.130000
PEG Ratio (5 yr expected) 1,NaN,1.750000,1.750000
Payout Ratio 4,29.160000,545.160000,287.160000
Price/Book (mrq),2.710000,1.700000,2.205000
Price/Sales (ttm),1.120000,2.040000,1.580000
Profit Margin,10.800000,15.800000,13.300000
Quarterly Earnings Growth (yoy),-54.900000,-39.400000,-47.150000
Quarterly Revenue Growth (yoy),-22.700000,6.500000,-8.100000
Return on Assets (ttm),7.170000,3.260000,5.215000
Return on Equity (ttm),24.140000,0.550000,12.345000
Revenue (ttm),350.000000,1935.000000,1142.500000
Revenue Per Share (ttm),45.020000,32.110000,38.565000
S&P500 52-Week Change 3,4.110000,4.110000,4.110000
Shares Outstanding 5,76.000000,572.870000,324.435000
"Shares Short (Aug 30, 2019) 4",3.856400,3.070000,3.463200
"Shares Short (prior month Jul 31, 2019) 4",3.531900,2.920000,3.225950
"Short % of Shares Outstanding (Aug 30, 2019) 4",0.510000,0.490000,0.500000
"Short Ratio (Aug 30, 2019) 4",1.270000,2.530000,1.900000
Total Cash (mrq),227.970000,616.000000,421.985000
Total Cash Per Share (mrq),2.990000,1.080000,2.035000
Total Debt (mrq),208.000000,1165.000000,686.500000
Total Debt/Equity (mrq),119.500000,50.100000,84.800000
Total Returns,-47.840000,-5.460000,-26.650000
Trailing Annual Dividend Rate 3,1.350000,1.690000,1.520000
Trailing Annual Dividend Yield 3,2.810000,2.460000,2.635000
Trailing P/E,11.060000,13.560000,12.310000

In [33]:
statistics_df = portfolio.statistics.dropna(how='all').T.sort_values("Diluted EPS (ttm)", ascending=False)[['Diluted EPS (ttm)', 'EBITDA', 'Levered Free Cash Flow (ttm)', 'Beta (3Y Monthly)', 'Profit Margin','Trailing Annual Dividend Yield 3']]

In [34]:
statistics_df

,Diluted EPS (ttm),EBITDA,Levered Free Cash Flow (ttm),Beta (3Y Monthly),Profit Margin,Trailing Annual Dividend Yield 3
NTR.TO,5.070,415.000,NaN,1.27,15.8,2.460
Averages,4.865,629.945,176.69,1.60,13.3,2.635
MX.TO,4.660,844.890,176.69,1.93,10.8,2.810

In [35]:
portfolio.cashflow(MX.cash_list)

In [36]:
portfolio.cashflow.dropna(how='all')

                                               MX.TO     NTR.TO
Adjustments To Net Income                   7.592929  -8.714844
Capital Expenditure                        -0.424791   0.154478
Change In Cash and Cash Equivalents        -0.828609 -18.725806
Changes In Accounts Receivables                  NaN  -1.590734
Changes In Inventories                           NaN   7.959596
Changes In Liabilities                           NaN  46.071429
Changes In Other Operating Activities      -1.051210 -30.526316
Depreciation                                0.258939   1.324088
Dividends Paid                              0.086967  -0.209302
Effect Of Exchange Rate Changes                  NaN  -0.000000
Investments                                      NaN  -0.000000
Net Borrowings                             -0.711004  33.777778
Net Income                                  1.836160   1.813386
Other Cash Flows from Financing Activities  0.418130  20.000000
Other Cash flows from Investing Activities -0.065812 -81.507463
Total Cash Flow From Operating Activities   2.300901  -0.122327
Total Cash Flows From Financing Activities  0.398150   2.145161
Total Cash Flows From Investing Activities -0.281296  -4.027259

In [37]:
portfolio.balance_sheet(MX.bs_list)

In [38]:
portfolio.balance_sheet.dropna(how='all')

                                         MX.TO      NTR.TO    Averages
Accounts Payable                      0.213855    6.166667    3.190261
Capital Surplus                      -0.341715    0.004348   -0.168683
Cash And Cash Equivalents             0.004484   24.428571   12.216527
Common Stock                         -0.123502    8.582141    4.229319
Deferred Long Term Asset Charges     -0.037960   20.600000   10.281020
Deferred Long Term Liability Charges       NaN    0.653061    0.653061
Goodwill                                   NaN  116.845361  116.845361
Intangible Assets                          NaN   22.263158   22.263158
Inventory                             0.532018    5.564753    3.048385
Long Term Debt                       -0.277907    1.046092    0.384092
Long Term Investments                -0.114691   -0.605748   -0.360219
Minority Interest                     0.192024         NaN    0.192024
Net Receivables                       0.020260    4.674024    2.347142
Net Tangible Assets                  -0.121249    0.316728    0.097739
Other Assets                         -0.051394    0.842105    0.395356
Other Current Liabilities             0.451079    3.704050    2.077564
Other Liabilities                    -0.052597    0.419008    0.183205
Other Stockholder Equity              1.966734    4.820000    3.393367
Property, plant and equipment        -0.042322    0.422646    0.190162
Retained Earnings                    -0.072951    0.199845    0.063447
Short/Current Long Term Debt          7.018406         NaN    7.018406
Total Assets                          0.011650    1.604728    0.808189
Total Current Assets                  0.213160    6.509337    3.361249
Total Current Liabilities             0.799755    3.771036    2.285396
Total Liabilities                     0.082635    1.319467    0.701051
Total stockholders' equity           -0.121249    1.913982    0.896367
Treasury Stock                        1.966734    4.820000    3.393367

In [39]:
portfolio.financials(MX.fin_list)

In [40]:
portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)

,Total Revenue,Cost of Revenue,Gross Profit,Selling General and Administrative,Others,Total Operating Expenses,Operating Income or Loss,Total Other Income/Expenses Net,Earnings Before Interest and Taxes,Interest Expense,Income Before Tax,Income Tax Expense,Minority Interest,Net Income From Continuing Ops,Discontinued Operations,Net Income,Net Income Applicable To Common Shares
MX.TO,0.766644,0.537715,1.923357,NaN,NaN,0.511254,3.799565,-1.448168,3.799565,0.351522,2.803492,12.957534,0.192024,2.251664,NaN,1.836160,1.836160
Averages,1.504113,1.668347,1.649867,10.205426,-0.136905,1.767410,2.059782,9.017144,2.059782,1.185020,0.862028,5.874507,0.192024,0.611931,22.251613,1.824773,1.824773
NTR.TO,2.241582,2.798978,1.376377,10.205426,-0.136905,3.023567,0.320000,19.482456,0.320000,2.018519,-1.079436,-1.208520,NaN,-1.027803,22.251613,1.813386,1.813386

In [41]:
GP = DataFrame(portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)['Gross Profit'])

In [42]:
Debt = portfolio.balance_sheet.dropna(how='all').T.sort_values('Long Term Debt', ascending=False)['Long Term Debt']

In [43]:
NI = portfolio.cashflow.dropna(how='all').T.sort_values("Net Income", ascending=False)['Net Income']

In [44]:
pandas.concat([statistics_df, NI, Debt, GP], axis=1, sort=True).sort_values('Gross Profit', ascending=False)

,Diluted EPS (ttm),EBITDA,Levered Free Cash Flow (ttm),Beta (3Y Monthly),Profit Margin,Trailing Annual Dividend Yield 3,Net Income,Long Term Debt,Gross Profit
MX.TO,4.660,844.890,176.69,1.93,10.8,2.810,1.836160,-0.277907,1.923357
Averages,4.865,629.945,176.69,1.60,13.3,2.635,NaN,0.384092,1.649867
NTR.TO,5.070,415.000,NaN,1.27,15.8,2.460,1.813386,1.046092,1.376377

In [45]:
cash_debt = MX.balance_sheet.T['Cash And Cash Equivalents'][0]/MX.balance_sheet.T['Long Term Debt'][0]

In [46]:
cash_debt*100

23.832356283382023

In [47]:
MX.balance_sheet.dropna(how='all')

Period Ending,12/31/2018,12/31/2017,12/31/2016,12/31/2015,Changes
MX.TO,,,,,
Cash And Cash Equivalents,256077.0,375479.0,223890.0,254934.0,0.004484
Net Receivables,514568.0,536636.0,499603.0,504350.0,0.020260
Inventory,387959.0,304464.0,281328.0,253234.0,0.532018
Other Current Assets,60931.0,NaN,NaN,NaN,NaN
Total Current Assets,1252076.0,1243127.0,1025667.0,1032078.0,0.213160
Long Term Investments,202441.0,193424.0,201904.0,228667.0,-0.114691
"Property, plant and equipment",3025095.0,2998326.0,3117469.0,3158782.0,-0.042322
Other Assets,129387.0,175865.0,211623.0,136397.0,-0.051394
Deferred Long Term Asset Charges,59532.0,102341.0,137341.0,61881.0,-0.037960
Total Assets,4608999.0,4610742.0,4556663.0,4555924.0,0.011650
Accounts Payable,617414.0,626817.0,523216.0,508639.0,0.213855
Short/Current Long Term Debt,383793.0,55905.0,53997.0,47864.0,7.018406
Other Current Liabilities,36914.0,65226.0,29720.0,25439.0,0.451079
Total Current Liabilities,1047353.0,747948.0,606933.0,581942.0,0.799755
Long Term Debt,1074493.0,1446366.0,1502209.0,1488026.0,-0.277907
Other Liabilities,490170.0,671317.0,642171.0,517383.0,-0.052597
Minority Interest,296628.0,244347.0,208515.0,248844.0,0.192024
Total Liabilities,2801158.0,2865631.0,2751313.0,2587351.0,0.082635
Common Stock,446544.0,480331.0,511465.0,509464.0,-0.123502
Retained Earnings,1145476.0,1088150.0,1124104.0,1235615.0,-0.072951
Treasury Stock,-82404.0,-69841.0,-41302.0,-27776.0,1.966734
Capital Surplus,1597.0,2124.0,2568.0,2426.0,-0.341715
Other Stockholder Equity,-82404.0,-69841.0,-41302.0,-27776.0,1.966734
Total stockholders' equity,1511213.0,1500764.0,1596835.0,1719729.0,-0.121249
Net Tangible Assets,1511213.0,1500764.0,1596835.0,1719729.0,-0.121249

In [50]:
MX.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list'],
 ['financials', 'fin_list'],
 ['cashflow', 'cash_list'],
 ['earnings_est',
  'revenue',
  'earnings_history',
  'eps_trend',
  'eps_revisions',
  'growth_estimates',
  'a_list']]

In [53]:
MX.earnings_est

,Current Qtr. (Dec 2018),Next Qtr. (Mar 2019),Current Year (2018),Next Year (2019)
Earnings Estimate,,,,
No. of Analysts,0.0,0.00,0.0,0.0
Avg. Estimate,0.0,0.00,0.0,0.0
Low Estimate,0.0,0.00,0.0,0.0
High Estimate,0.0,0.00,0.0,0.0
Year Ago EPS,1.7,2.03,NaN,NaN