In [1]:
from finance_python.stock import stock
from finance_python.industry import industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
symbols = ['CWB.TO', 'LB.TO','TD.TO']
start = date.today() - timedelta(days=365)
end = date.today()

In [3]:
stock_loop = lambda x: stock(x, start, end)

In [4]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

20.89849829673767

In [31]:
CWB = stocks[0]
LB = stocks[1]
TD = stocks[2]

In [32]:
CWB.description

'Canadian Western Bank provides personal and business banking products and services primarily in Western Canada. The company offers current, savings, cash management, US dollar, senior, chequing, youth, and student accounts, as well as specialized accounts, including corporate and commercial, organization, strata solution/condo, general trust, and trust fund investment accounts. It also provides leading products, such as commercial lending and real estate, energy lending, and equipment financing products; mortgages; secured and unsecured lines of credit; registered retirement savings plan (RRSP), consolidation, car, and recreation vehicle loans; personal lines of credit; and credit cards. In addition, the company offers cash management services; life and disability insurance products that cover various loans, including residential mortgages, home improvement loans, collateral mortgages, lease loans, commercial mortgages, car loans, debt consolidation, education loans, investment loans, business loans, home equity lines of credit, business leases, personal lines of credit, and business lines of credit; and ATM, telephone, mobile, and online banking services, as well as deposit register and cheque order services. Further, it provides investment products comprising guaranteed investment certificates, RRSPs, registered retirement income funds, tax-free savings accounts, registered education savings plans, and mutual funds, as well as personal and business planning services. The company was founded in 1984 and is headquartered in Edmonton, Canada.'

In [33]:
LB.description

'Laurentian Bank of Canada, together with its subsidiaries, provides banking services to individuals, small and medium-sized enterprises, and independent advisors in Canada and the United States. It operates through four segments: Retail Services, Business Services, B2B Bank, and Capital Markets. The company offers transactional products and current accounts, term deposits, and investment accounts; personal line of credit, personal loans, student loans, and registered retirement savings plans; financing for agriculture, real estate, and commercial industries, as well as small and medium-sized enterprises; mortgage solutions, such as variable-rate mortgage, fixed-rate mortgage, equity line of credit, mortgage insurance, and retirement line of credit; and credit and business cards, as well as equipment finance solutions. It also provides investment products, including fixed-rate investments, indexed investments, mutual funds, systematic savings plans, retirement projection plans, registered plans, bank securities, deposit-insurance, and power-of-attorneys; short-term and long-term investment solutions; and guaranteed investment certificates, as well as offers credit insurance products. In addition, the company offers leasing solutions, cash management and international services, and electronic banking services. Laurentian Bank of Canada was founded in 1846 and is headquartered in Montr√©al, Canada.'

In [34]:
TD.description

"The Toronto-Dominion Bank, together with its subsidiaries, provides various personal and commercial banking products and services in Canada and the United States. The company operates through three segments: Canadian Retail, U.S. Retail, and Wholesale Banking. It offers personal deposits, such as checking, savings, and investment products; financing, investment, cash management, international trade, and day-to-day banking services to businesses; financing options to customers at point of sale for automotive and recreational vehicle purchases through auto dealer network; credit cards; investing, advice-based, and asset management services to retail and institutional clients; and property and casualty insurance, as well as life and health insurance products. The company also provides capital markets, and corporate and investment banking services, including underwriting and distribution of new debt and equity issues; providing advice on strategic acquisitions and divestitures; and trading, funding, and investment services to companies, governments, and institutions, as well as automated teller machines, telephone, Internet, and mobile banking services. The company offers its products and services under the TD Bank, America's Most Convenient Bank, and TD Securities brand names. It offers personal and business banking products and services through a network of 1,098 branches and 3,394 automated teller machines in Canada; and through a network of 1,257 stores. The Toronto-Dominion Bank was founded in 1855 and is headquartered in Toronto, Canada."

In [8]:
bmo.sector
bns.sector

'Banks - Regional - Canada'

In [9]:
bmo.history
bns.history
print(bmo.price)
print(bns.price)

31.19
44.41

In [10]:
print(bmo.dividends,bns.dividends)

[                                                Date      Dividends
0                                       Jun 12, 2019  0.27 Dividend
1                                       Mar 14, 2019  0.27 Dividend
2                                       Dec 13, 2018  0.26 Dividend
3                                       Sep 13, 2018  0.26 Dividend
4  *Close price adjusted for splits.**Adjusted cl...            NaN] [                                                Date      Dividends
0                                       Jun 28, 2019  0.66 Dividend
1                                       Mar 29, 2019  0.65 Dividend
2                                       Dec 31, 2018  0.65 Dividend
3                                       Sep 28, 2018  0.64 Dividend
4  *Close price adjusted for splits.**Adjusted cl...            NaN]

In [11]:
bmo.stats()
bns.stats()

In [12]:
bns.statistics

                                                 LB.TO
Market Cap (intraday) 5                         189.00
Enterprise Value 3                                 NaN
Trailing P/E                                     10.52
Forward P/E 1                                     9.03
PEG Ratio (5 yr expected) 1                      -2.43
Price/Sales (ttm)                                 1.97
Price/Book (mrq)                                  0.81
Enterprise Value/Revenue 3                       10.75
Enterprise Value/EBITDA 6                          NaN
Beta (3Y Monthly)                                 1.15
52-Week Change 3                                 -5.73
S&P500 52-Week Change 3                          -0.90
52 Week High 3                                   47.40
52 Week Low 3                                    36.21
50-Day Moving Average 3                          44.98
200-Day Moving Average 3                         43.39
Avg Vol (3 month) 3                                NaN
Avg Vol (10 day) 3                                 NaN
Shares Outstanding 5                             41.25
Float                                            42.26
% Held by Insiders 1                               NaN
% Held by Institutions 1                           NaN
Shares Short (Aug 15, 2019) 4                     3.54
Short Ratio (Aug 15, 2019) 4                     19.32
Short % of Float (Aug 15, 2019) 4                  NaN
Short % of Shares Outstanding (Aug 15, 2019) 4    7.71
Shares Short (prior month Jul 15, 2019) 4         3.69
Forward Annual Dividend Rate 4                    2.64
Forward Annual Dividend Yield 4                   5.94
Trailing Annual Dividend Rate 3                   2.58
Trailing Annual Dividend Yield 3                  5.81
5 Year Average Dividend Yield 4                   4.82
Payout Ratio 4                                   61.58
Dividend Date 3                                    NaN
Ex-Dividend Date 4                                 NaN
Last Split Factor (new per old) 2                  NaN
Last Split Date 3                                  NaN
Fiscal Year Ends                                   NaN
Most Recent Quarter (mrq)                          NaN
Profit Margin                                    19.79
Operating Margin (ttm)                           24.24
Return on Assets (ttm)                            0.41
Return on Equity (ttm)                            7.58
Revenue (ttm)                                   956.54
Revenue Per Share (ttm)                          22.74
Quarterly Revenue Growth (yoy)                   -7.90
Gross Profit (ttm)                              999.41
EBITDA                                             NaN
Net Income Avi to Common (ttm)                  176.25
Diluted EPS (ttm)                                 4.19
Quarterly Earnings Growth (yoy)                 -26.80
Total Cash (mrq)                                   NaN
Total Cash Per Share (mrq)                       79.79
Total Debt (mrq)                                   NaN
Total Debt/Equity (mrq)                            NaN
Current Ratio (mrq)                                NaN
Book Value Per Share (mrq)                       54.52
Operating Cash Flow (ttm)                          NaN
Levered Free Cash Flow (ttm)                       NaN

In [13]:
bmo.statistics

                                                CWB.TO
Market Cap (intraday) 5                         276.00
Enterprise Value 3                                 NaN
Trailing P/E                                     11.00
Forward P/E 1                                     9.32
PEG Ratio (5 yr expected) 1                       1.53
Price/Sales (ttm)                                 3.55
Price/Book (mrq)                                  1.12
Enterprise Value/Revenue 3                        5.58
Enterprise Value/EBITDA 6                          NaN
Beta (3Y Monthly)                                 1.75
52-Week Change 3                                -18.16
S&P500 52-Week Change 3                          -0.90
52 Week High 3                                   37.00
52 Week Low 3                                    24.33
50-Day Moving Average 3                          29.82
200-Day Moving Average 3                         29.40
Avg Vol (3 month) 3                                NaN
Avg Vol (10 day) 3                                 NaN
Shares Outstanding 5                             66.64
Float                                            86.73
% Held by Insiders 1                               NaN
% Held by Institutions 1                           NaN
Shares Short (Aug 15, 2019) 4                     1.50
Short Ratio (Aug 15, 2019) 4                      8.79
Short % of Float (Aug 15, 2019) 4                  NaN
Short % of Shares Outstanding (Aug 15, 2019) 4    1.93
Shares Short (prior month Jul 15, 2019) 4         1.45
Forward Annual Dividend Rate 4                    1.08
Forward Annual Dividend Yield 4                   3.53
Trailing Annual Dividend Rate 3                   1.04
Trailing Annual Dividend Yield 3                  3.33
5 Year Average Dividend Yield 4                   3.14
Payout Ratio 4                                   36.11
Dividend Date 3                                    NaN
Ex-Dividend Date 4                                 NaN
Last Split Factor (new per old) 2                  NaN
Last Split Date 3                                  NaN
Fiscal Year Ends                                   NaN
Most Recent Quarter (mrq)                          NaN
Profit Margin                                    34.87
Operating Margin (ttm)                           49.98
Return on Assets (ttm)                            0.94
Return on Equity (ttm)                           10.14
Revenue (ttm)                                   778.69
Revenue Per Share (ttm)                           8.81
Quarterly Revenue Growth (yoy)                    5.40
Gross Profit (ttm)                              755.10
EBITDA                                             NaN
Net Income Avi to Common (ttm)                  255.33
Diluted EPS (ttm)                                 2.88
Quarterly Earnings Growth (yoy)                   5.30
Total Cash (mrq)                                625.37
Total Cash Per Share (mrq)                        7.17
Total Debt (mrq)                                   NaN
Total Debt/Equity (mrq)                            NaN
Current Ratio (mrq)                                NaN
Book Value Per Share (mrq)                       28.20
Operating Cash Flow (ttm)                          NaN
Levered Free Cash Flow (ttm)                       NaN

In [14]:
bmo.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list']]

In [15]:
bns.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list']]

In [16]:
bmo.balance()
bns.balance()

In [17]:
bns.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list']]

In [18]:
bns.balance_sheet

Period Ending,10/31/2018,10/31/2017,10/31/2016,10/31/2015,Changes
LB.TO,,,,,
Current Assets,NaN,NaN,NaN,NaN,NaN
Cash And Cash Equivalents,116490.0,111978.0,123716.0,109055.0,0.068177
Short Term Investments,4026735.0,3323225.0,2943369.0,4003248.0,0.005867
Net Receivables,158478.0,138309.0,216978.0,107826.0,0.469757
Inventory,12500.0,6200.0,6400.0,8900.0,0.404494
Other Current Assets,386576.0,875492.0,698304.0,536519.0,-0.279474
Total Current Assets,7490202.0,6708397.0,6656065.0,6767527.0,0.106786
Long Term Investments,3366006.0,3437247.0,3225925.0,2761979.0,0.218694
"Property, plant and equipment",96341.0,60834.0,76079.0,45562.0,1.114503
Goodwill,116617.0,118100.0,55812.0,34853.0,2.345967
Intangible Assets,367345.0,293422.0,150490.0,147135.0,1.496653
Accumulated Amortization,NaN,NaN,NaN,NaN,NaN
Other Assets,34458172.0,36064658.0,32841969.0,29902448.0,0.152353
Deferred Long Term Asset Charges,25437.0,38702.0,36495.0,17450.0,0.457708
Total Assets,45894683.0,46682658.0,43006340.0,39659504.0,0.157218
Current Liabilities,NaN,NaN,NaN,NaN,NaN
Accounts Payable,28481433.0,29435662.0,27993425.0,26873161.0,0.059847
Short/Current Long Term Debt,NaN,1519688.0,1377678.0,1516157.0,NaN
Other Current Liabilities,3461631.0,2944470.0,2420249.0,2404378.0,0.439720
Total Current Liabilities,35200931.0,37207650.0,34855669.0,33588899.0,0.047993
Long Term Debt,8136515.0,7059660.0,6066600.0,4427086.0,0.837894
Other Liabilities,61035.0,84938.0,109244.0,56492.0,0.080418
Deferred Long Term Liability Charges,NaN,NaN,NaN,NaN,NaN
Minority Interest,NaN,NaN,NaN,NaN,NaN
Negative Goodwill,NaN,NaN,NaN,NaN,NaN
Total Liabilities,43398481.0,44352248.0,41031513.0,38072477.0,0.139891
Stockholders' Equity,NaN,NaN,NaN,NaN,NaN
Misc. Stocks Options Warrants,NaN,NaN,NaN,NaN,NaN
Redeemable Preferred Stock,NaN,NaN,NaN,NaN,NaN
Preferred Stock,NaN,NaN,NaN,NaN,NaN
Common Stock,1115416.0,953536.0,696493.0,466336.0,1.391872
Retained Earnings,1152470.0,1035770.0,924861.0,886656.0,0.299794
Treasury Stock,-15722.0,-496.0,11873.0,14402.0,-2.091654
Capital Surplus,NaN,NaN,NaN,NaN,NaN
Other Stockholder Equity,-15722.0,-496.0,11873.0,14402.0,-2.091654
Total stockholders' equity,2252164.0,1988810.0,1633227.0,1367394.0,0.647048
Net Tangible Assets,1768202.0,1577288.0,1426925.0,1185406.0,0.491643

In [19]:
bns.cash()
bmo.cash()

In [20]:
bns.cashflow

Period Ending,10/31/2018,10/31/2017,10/31/2016,10/31/2015,Changes
LB.TO,,,,,
Net Income,224646.0,206461.0,151910.0,102470.0,1.192310
"Operating Activities, Cash Flows Provided By or Used In",NaN,NaN,NaN,NaN,NaN
Depreciation,22985.0,15576.0,13120.0,17396.0,0.321281
Adjustments To Net Income,-44341.0,-337.0,276248.0,-83620.0,-0.469732
Changes In Accounts Receivables,NaN,NaN,NaN,NaN,NaN
Changes In Liabilities,NaN,NaN,NaN,NaN,NaN
Changes In Inventories,NaN,NaN,NaN,NaN,NaN
Changes In Other Operating Activities,843551.0,-948966.0,675542.0,-1728502.0,-1.488024
Total Cash Flow From Operating Activities,520604.0,-309504.0,477182.0,-1540328.0,-1.337983
"Investing Activities, Cash Flows Provided By or Used In",NaN,NaN,NaN,NaN,NaN
Capital Expenditure,-53276.0,-101918.0,-43549.0,-14619.0,2.644299
Investments,-98162.0,-266377.0,-423904.0,142235.0,-1.690140
Other Cash flows from Investing Activities,NaN,NaN,NaN,NaN,NaN
Total Cash Flows From Investing Activities,448291.0,-1365830.0,-1463953.0,-485504.0,-1.923352
"Financing Activities, Cash Flows Provided By or Used In",NaN,NaN,NaN,NaN,NaN
Dividends Paid,-88722.0,-75215.0,-55209.0,-73025.0,0.214954
Sale Purchase of Stock,NaN,NaN,NaN,NaN,NaN
Net Borrowings,NaN,148306.0,-250000.0,-250000.0,NaN
Other Cash Flows from Financing Activities,-917942.0,1357015.0,966008.0,2081278.0,-1.441047
Total Cash Flows From Financing Activities,-967542.0,1660587.0,1001432.0,2008640.0,-1.481690
Effect Of Exchange Rate Changes,3159.0,3009.0,3009.0,3009.0,0.049850
Change In Cash and Cash Equivalents,4512.0,-11738.0,14661.0,-17192.0,-1.262448

In [21]:
bns.analyze()

In [22]:
bmo.analyze()

In [23]:
bns.attributes
bmo.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list'],
 ['cashflow', 'cash_list'],
 ['earnings_est',
  'revenue',
  'earnings_history',
  'eps_trend',
  'eps_revisions',
  'growth_estimates',
  'a_list']]

In [24]:
bns.earnings_est

,Current Qtr. (Jul 2019),Next Qtr. (Oct 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,11.00,9.00,11.00,11.00
Avg. Estimate,1.16,1.20,4.42,4.88
Low Estimate,1.14,1.15,4.37,4.57
High Estimate,1.20,1.26,4.48,5.15
Year Ago EPS,1.34,1.22,5.51,4.42

In [25]:
bmo.revenue

,Current Qtr. (Jul 2019),Next Qtr. (Oct 2019),Current Year (2019),Next Year (2020)
Revenue Estimate,,,,
No. of Analysts,12,7,13,13
Avg. Estimate,219.61M,224.24M,866.39M,934.87M
Low Estimate,216.9M,221.51M,852.7M,902.8M
High Estimate,221.7M,227.5M,875M,974M
Year Ago Sales,204.99M,208.57M,803.36M,866.39M
Sales Growth (year/est),7.10%,7.50%,7.80%,7.90%

In [26]:
bns.financial()

In [27]:
bns.financials

Period Ending,10/31/2018,10/31/2017,10/31/2016,10/31/2015,Changes
LB.TO,,,,,
Total Revenue,999410.0,959410.0,879001.0,862226.0,0.159104
Cost of Revenue,NaN,NaN,7064.0,6893.0,NaN
Gross Profit,999410.0,959410.0,871937.0,855333.0,0.168446
Operating Expenses,NaN,NaN,NaN,NaN,NaN
Research Development,NaN,NaN,NaN,NaN,NaN
Selling General and Administrative,594006.0,576969.0,542386.0,558943.0,0.062731
Non Recurring,NaN,NaN,NaN,NaN,NaN
Others,116770.0,89197.0,92536.0,84578.0,0.380619
Total Operating Expenses,710776.0,666166.0,641986.0,650414.0,0.092806
Operating Income or Loss,288634.0,293244.0,237015.0,211812.0,0.362690
Income from Continuing Operations,NaN,NaN,NaN,NaN,NaN
Total Other Income/Expenses Net,-8301.0,-26576.0,-39653.0,-78409.0,-0.894132
Earnings Before Interest and Taxes,NaN,NaN,NaN,NaN,NaN
Interest Expense,NaN,NaN,NaN,NaN,NaN
Income Before Tax,280333.0,266668.0,197362.0,133403.0,1.101400
Income Tax Expense,55687.0,60207.0,45452.0,30933.0,0.800246
Minority Interest,NaN,NaN,NaN,NaN,NaN
Net Income From Continuing Ops,224646.0,206461.0,151910.0,102470.0,1.192310
Non-recurring Events,NaN,NaN,NaN,NaN,NaN
Discontinued Operations,NaN,NaN,NaN,NaN,NaN
Extraordinary Items,NaN,NaN,NaN,NaN,NaN
Effect Of Accounting Changes,NaN,NaN,NaN,NaN,NaN
Other Items,NaN,NaN,NaN,NaN,NaN
Net Income,NaN,NaN,NaN,NaN,1.192310
Net Income,224646.0,206461.0,151910.0,102470.0,1.192310
Preferred Stock And Other Adjustments,NaN,NaN,NaN,NaN,NaN
Net Income Applicable To Common Shares,210608.0,189365.0,138597.0,92868.0,1.267821

In [28]:
bns.attributes

[['dividends', 'sector', 'description', 'history', 'price'],
 ['stats()', 'balance()', 'financial()', 'cash()', 'analyze()'],
 ['statistics', 'stats_list'],
 ['balance_sheet', 'bs_list'],
 ['cashflow', 'cash_list'],
 ['earnings_est',
  'revenue',
  'earnings_history',
  'eps_trend',
  'eps_revisions',
  'growth_estimates',
  'a_list'],
 ['financials', 'fin_list']]

In [29]:
banks = industry()
banks.attributes

[]

In [30]:
banks.statistics(bns.stats_list)
banks.statistics
banks.attributes

['statistics']