In [1]:
from finance_python.stock import stock
from finance_python.industry import industry
import sys, os, time
import numpy as np
import pandas
from datetime import datetime, date, timedelta
from pandas import DataFrame

In [2]:
symbols = ["ATD-B.TO", "L.TO", "MRU.TO", "EMP-A.TO"]

start = date.today() - timedelta(days=365)
end = date.today()

In [3]:
ATD_A = stock("ATD-A.TO", start, end)

In [4]:
EMP_B = stock("EMP-B.TO", start, end)

EMP-B.TO : Error cleaning history dataframe. Is it the right symbol?

In [5]:
stock_loop = lambda x: stock(x, start, end)
stat = lambda x: stocks[x].stats()
bal = lambda x: stocks[x].balance()
fin = lambda x: stocks[x].financial()
ca = lambda x: stocks[x].cash()
an = lambda x: stocks[x].analyze()

In [6]:
timer_start = time.time()

stocks = list(map(stock_loop, symbols))

timer_end = time.time()
print(timer_end - timer_start)

13.968446969985962

In [7]:
timer_start = time.time()

for each in range(0, len(stocks)):
    stat(each)
    
timer_end = time.time()
print(timer_end - timer_start)

C:\Users\rayde\iCloudDrive\GitHub\finance_python\statistics.py:73: RuntimeWarning: divide by zero encountered in double_scalars
  returns_adj = abs(div_r/float(beta))

2.368356466293335

In [8]:
timer_start = time.time()

for each in range(0, len(stocks)):
    bal(each)
    
timer_end = time.time()
print(timer_end - timer_start)

1.6312675476074219

In [9]:
timer_start = time.time()

for each in range(0, len(stocks)):
    fin(each)
    
timer_end = time.time()
print(timer_end - timer_start)

2.588078737258911

In [10]:
timer_start = time.time()

for each in range(0, len(stocks)):
    ca(each)
    
timer_end = time.time()
print(timer_end - timer_start)

1.5977659225463867

In [11]:
timer_start = time.time()

for each in range(0, len(stocks)):
    an(each)
    
timer_end = time.time()
print(timer_end - timer_start)

3.563506603240967

In [12]:
ATD, L, MRU, EMP = stocks

In [13]:
price = list(map(lambda symbol, x: {symbol: stocks[x].price}, symbols, range(0, len(symbols))))

In [15]:
L.description

"Loblaw Companies Limited, a food and pharmacy company, engages in the grocery, pharmacy, health and beauty, apparel, general merchandise, financial services, and wireless mobile products and services businesses in Canada. It operates in two segments, Retail and Financial Services. The Retail segment operates corporate and franchise-owned retail food, and associate-owned drug stores comprising in-store pharmacies, other health and beauty product stores, apparel stores, and other general merchandise stores, as well as supports the PC Optimum reward program. The Financial Services segment provides credit card services, the PC Optimum reward program, insurance brokerage services, deposit taking services, and telecommunication services. Loblaw Companies Limited provides its products and services under the President's Choice, Life Brand, and no name brands. The company was founded in 1919 and is headquartered in Brampton, Canada. Loblaw Companies Limited is a subsidiary of George Weston Limited."

In [16]:
price

[{'ATD-B.TO': 85.42},
 {'L.TO': 74.22},
 {'MRU.TO': 57.89},
 {'EMP-A.TO': '37.10'}]

In [17]:
L.description

"Loblaw Companies Limited, a food and pharmacy company, engages in the grocery, pharmacy, health and beauty, apparel, general merchandise, financial services, and wireless mobile products and services businesses in Canada. It operates in two segments, Retail and Financial Services. The Retail segment operates corporate and franchise-owned retail food, and associate-owned drug stores comprising in-store pharmacies, other health and beauty product stores, apparel stores, and other general merchandise stores, as well as supports the PC Optimum reward program. The Financial Services segment provides credit card services, the PC Optimum reward program, insurance brokerage services, deposit taking services, and telecommunication services. Loblaw Companies Limited provides its products and services under the President's Choice, Life Brand, and no name brands. The company was founded in 1919 and is headquartered in Brampton, Canada. Loblaw Companies Limited is a subsidiary of George Weston Limited."

In [18]:
print(ATD.earnings_history)
print(L.earnings_history) 
print(MRU.earnings_history) 
print(EMP.earnings_history)

                 10/30/2018 1/30/2019 4/29/2019 7/30/2019
Earnings History
EPS Est.               0.82      1.17      0.54      0.95
EPS Actual             0.84      1.08      0.52      0.97
Difference             0.02     -0.09     -0.02      0.02
Surprise %            2.40%    -7.70%    -3.70%     2.10%
                 9/29/2018 12/30/2018 3/30/2019 6/29/2019
Earnings History
EPS Est.              1.44       1.04       0.8      1.01
EPS Actual            1.49       1.07      0.78      1.01
Difference            0.05       0.03     -0.02         0
Surprise %           3.50%      2.90%    -2.50%     0.00%
                 9/29/2018 12/30/2018 3/30/2019 6/29/2019
Earnings History
EPS Est.              0.63       0.67      0.63      0.91
EPS Actual            0.63       0.67       0.6       0.9
Difference               0          0     -0.03     -0.01
Surprise %           0.00%      0.00%    -4.80%    -1.10%
                 7/30/2018 10/30/2018 1/30/2019 4/29/2019
Earnings History
EPS Est.              0.42       0.32      0.31      0.42
EPS Actual            0.37        0.4      0.27      0.46
Difference           -0.05       0.08     -0.04      0.04
Surprise %         -11.90%     25.00%   -12.90%     9.50%

In [19]:
ATD.dividends

[                                                Date       Dividends
 0                                       Jul 17, 2019  0.125 Dividend
 1                                       Mar 27, 2019  0.125 Dividend
 2                                       Dec 05, 2018    0.1 Dividend
 3                                       Sep 13, 2018    0.1 Dividend
 4  *Close price adjusted for splits.**Adjusted cl...             NaN]

In [20]:
ATD.statistics.dropna(how='all')

                                                   ATD-B.TO
Market Cap (intraday) 5                         4798.000000
Enterprise Value 3                              5691.000000
Trailing P/E                                      25.540000
Forward P/E 1                                     24.740000
PEG Ratio (5 yr expected) 1                        2.230000
Price/Sales (ttm)                                  0.820000
Price/Book (mrq)                                   5.190000
Enterprise Value/Revenue 3                         0.970000
Enterprise Value/EBITDA 6                         15.880000
Beta (3Y Monthly)                                  0.310000
52-Week Change 3                                  29.440000
S&P500 52-Week Change 3                            3.530000
52 Week High 3                                    88.400000
52 Week Low 3                                     60.030000
50-Day Moving Average 3                           81.980000
200-Day Moving Average 3                          80.860000
Avg Vol (3 month) 3                                8.550600
Avg Vol (10 day) 3                                 8.166100
Shares Outstanding 5                             437.500000
Float                                            437.870000
Shares Short (Aug 15, 2019) 4                      3.060000
Short Ratio (Aug 15, 2019) 4                       4.250000
Short % of Shares Outstanding (Aug 15, 2019) 4     0.610000
Shares Short (prior month Jul 15, 2019) 4          3.010000
Forward Annual Dividend Rate 4                     0.500000
Forward Annual Dividend Yield 4                    0.590000
Trailing Annual Dividend Rate 3                    0.350000
Trailing Annual Dividend Yield 3                   0.410000
5 Year Average Dividend Yield 4                    0.490000
Payout Ratio 4                                    10.070000
Profit Margin                                      3.280000
Operating Margin (ttm)                             4.530000
Return on Assets (ttm)                             6.860000
Return on Equity (ttm)                            21.520000
Revenue (ttm)                                   5849.000000
Revenue Per Share (ttm)                          103.660000
Quarterly Revenue Growth (yoy)                    -4.200000
Gross Profit (ttm)                               919.000000
EBITDA                                           358.000000
Net Income Avi to Common (ttm)                   192.000000
Diluted EPS (ttm)                                  3.390000
Quarterly Earnings Growth (yoy)                   18.300000
Total Cash (mrq)                                 106.000000
Total Cash Per Share (mrq)                         1.880000
Total Debt (mrq)                                 964.000000
Total Debt/Equity (mrq)                           99.800000
Current Ratio (mrq)                                0.810000
Book Value Per Share (mrq)                        16.690000
Operating Cash Flow (ttm)                        323.000000
Adjusted Returns                                   1.903226
Total Returns                                     30.030000

In [21]:
ATD.cashflow.dropna()

Period Ending,4/28/2019,4/29/2018,4/30/2017,4/24/2016,Changes
ATD-B.TO,,,,,
Net Income,1833900.0,1670600.0,1208900.0,1191200.0,0.539540
Depreciation,965300.0,891600.0,639500.0,609600.0,0.583497
Adjustments To Net Income,159200.0,-199300.0,60800.0,-3000.0,-54.066667
Changes In Accounts Receivables,40200.0,-299700.0,-178200.0,53500.0,-0.248598
Changes In Liabilities,205900.0,343900.0,255900.0,-4800.0,-43.895833
Changes In Inventories,-126300.0,-204500.0,-40600.0,24700.0,-6.113360
Changes In Other Operating Activities,14800.0,-14400.0,3400.0,1000.0,13.800000
Total Cash Flow From Operating Activities,3083600.0,2163100.0,1925500.0,1887900.0,0.633349
Capital Expenditure,-1145100.0,-1169300.0,-994100.0,-905700.0,0.264326
Other Cash flows from Investing Activities,-16900.0,-13500.0,14200.0,400.0,-43.250000
Total Cash Flows From Investing Activities,-935200.0,-5444500.0,-2387500.0,-1181300.0,-0.208330
Dividends Paid,-181300.0,-162400.0,-145300.0,-104100.0,0.741595
Net Borrowings,-1405700.0,7650600.0,646200.0,-577500.0,1.434113
Other Cash Flows from Financing Activities,-467000.0,-4018300.0,-5800.0,-21800.0,20.422018
Total Cash Flows From Financing Activities,-2053800.0,3277000.0,498400.0,-702600.0,1.923143
Effect Of Exchange Rate Changes,-54400.0,33000.0,1800.0,19600.0,-3.775510
Change In Cash and Cash Equivalents,40200.0,28600.0,38200.0,23600.0,0.703390

In [22]:
portfolio = industry()

In [23]:
portfolio.statistics(ATD.stats_list)

In [24]:
stats = portfolio.statistics
stats

,ATD-B.TO,L.TO,MRU.TO,EMP-A.TO,Averages
200-Day Moving Average 3,80.860000,67.950000,50.460000,32.040000,57.827500
5 Year Average Dividend Yield 4,0.490000,1.570000,1.400000,1.650000,1.277500
50-Day Moving Average 3,81.980000,70.570000,53.700000,35.970000,60.555000
52 Week High 3,88.400000,74.790000,58.350000,37.430000,64.742500
52 Week Low 3,60.030000,50.260000,39.040000,22.380000,42.927500
52-Week Change 3,29.440000,36.340000,43.720000,48.820000,39.580000
Adjusted Returns,1.903226,5.862069,inf,5.863636,inf
Avg Vol (10 day) 3,8.166100,5.468600,5.731600,3.520600,5.721725
Avg Vol (3 month) 3,8.550600,4.811000,4.406600,4.453900,5.555525
Beta (3Y Monthly),0.310000,0.290000,0.000000,-0.220000,0.095000
Book Value Per Share (mrq),16.690000,30.290000,23.140000,14.740000,21.215000
Current Ratio (mrq),0.810000,1.340000,1.490000,0.980000,1.155000
Diluted EPS (ttm),3.390000,2.160000,2.690000,1.420000,2.415000
EBITDA,358.000000,344.000000,132.000000,101.000000,233.750000
Enterprise Value 3,5691.000000,4287.000000,1711.000000,1162.000000,3212.750000
Enterprise Value/EBITDA 6,15.880000,12.460000,12.950000,11.540000,13.207500
Enterprise Value/Revenue 3,0.970000,0.910000,1.030000,0.460000,0.842500
Float,437.870000,172.230000,253.460000,158.720000,255.570000
Forward Annual Dividend Rate 4,0.500000,1.260000,0.800000,0.480000,0.760000
Forward Annual Dividend Yield 4,0.590000,1.700000,1.380000,1.290000,1.240000
Forward P/E 1,24.740000,15.850000,18.260000,16.360000,18.802500
Gross Profit (ttm),919.000000,1416.000000,156.000000,619.000000,777.500000
Levered Free Cash Flow (ttm),NaN,NaN,345.910000,345.180000,345.545000
Market Cap (intraday) 5,4798.000000,2677.000000,1435.000000,995.000000,2476.250000
Net Income Avi to Common (ttm),192.000000,686.000000,689.200000,387.300000,488.625000
Operating Cash Flow (ttm),323.000000,339.000000,709.700000,885.600000,564.325000
Operating Margin (ttm),4.530000,4.540000,6.300000,2.530000,4.475000
PEG Ratio (5 yr expected) 1,2.230000,6.280000,2.280000,1.230000,3.005000
Payout Ratio 4,10.070000,65.220000,29.460000,30.990000,33.935000
Price/Book (mrq),5.190000,2.460000,2.500000,2.510000,3.165000
Price/Sales (ttm),0.820000,0.570000,0.860000,0.390000,0.660000
Profit Margin,3.280000,1.740000,4.140000,1.530000,2.672500
Quarterly Earnings Growth (yoy),18.300000,445.300000,32.100000,72.000000,141.925000
Quarterly Revenue Growth (yoy),-4.200000,2.900000,12.800000,5.800000,4.325000
Return on Assets (ttm),6.860000,3.560000,5.990000,4.370000,5.195000
Return on Equity (ttm),21.520000,6.260000,12.100000,10.600000,12.620000
Revenue (ttm),5849.000000,4733.000000,1664.000000,2525.000000,3692.750000
Revenue Per Share (ttm),103.660000,127.530000,65.310000,92.850000,97.337500
S&P500 52-Week Change 3,3.530000,3.530000,3.530000,3.530000,3.530000
Shares Outstanding 5,437.500000,366.100000,253.990000,173.660000,307.812500
"Shares Short (Aug 15, 2019) 4",3.060000,11.330000,2.000000,1.940000,4.582500
"Shares Short (prior month Jul 15, 2019) 4",3.010000,11.070000,1.560000,1.130000,4.192500
"Short % of Shares Outstanding (Aug 15, 2019) 4",0.610000,3.100000,0.760000,0.760000,1.307500
"Short Ratio (Aug 15, 2019) 4",4.250000,22.830000,4.620000,4.850000,9.137500
Total Cash (mrq),106.000000,119.000000,263.300000,553.300000,260.400000
Total Cash Per Share (mrq),1.880000,3.260000,1.040000,2.040000,2.055000
Total Debt (mrq),964.000000,1664.000000,266.000000,202.000000,774.000000
Total Debt/Equity (mrq),99.800000,146.600000,45.120000,49.490000,85.252500
Total Returns,30.030000,38.040000,45.100000,50.110000,40.820000
Trailing Annual Dividend Rate 3,0.350000,1.200000,0.780000,0.440000,0.692500
Trailing Annual Dividend Yield 3,0.410000,1.620000,1.350000,1.190000,1.142500
Trailing P/E,25.540000,34.440000,21.550000,26.040000,26.892500

In [25]:
temp = portfolio.statistics.T["Market Cap (intraday) 5"].sort_values(ascending=False)

In [26]:
temp = portfolio.statistics.T["Market Cap (intraday) 5"].sort_values(ascending=False)

In [27]:
temp[0] = 3778
temp[1] = 1101

In [28]:
temp

ATD-B.TO    3778.00
L.TO        1101.00
Averages    2476.25
MRU.TO      1435.00
EMP-A.TO     995.00
Name: Market Cap (intraday) 5, dtype: float64

In [29]:
portfolio.statistics.T['Shares Outstanding 5'].sort_values(ascending=False)

ATD-B.TO    437.5000
L.TO        366.1000
Averages    307.8125
MRU.TO      253.9900
EMP-A.TO    173.6600
Name: Shares Outstanding 5, dtype: float64

In [30]:
temp/portfolio.statistics.T['Shares Outstanding 5']

ATD-B.TO    8.635429
Averages    8.044670
EMP-A.TO    5.729587
L.TO        3.007375
MRU.TO      5.649829
dtype: float64

In [31]:
portfolio.cashflow(ATD.cash_list)

In [32]:
portfolio.cashflow.dropna(how='all')

,ATD-B.TO,L.TO,MRU.TO,EMP-A.TO
Adjustments To Net Income,-54.066667,0.362954,68.969512,-0.976509
Capital Expenditure,0.264326,0.001984,0.300455,-0.333171
Change In Cash and Cash Equivalents,0.703390,-39.578947,-6.379310,1.391026
Changes In Accounts Receivables,-0.248598,NaN,NaN,NaN
Changes In Inventories,-6.113360,NaN,NaN,NaN
Changes In Liabilities,-43.895833,NaN,NaN,NaN
Changes In Other Operating Activities,13.800000,-13.613333,-6.122642,-1.124811
Depreciation,0.583497,-0.031364,0.292824,-0.133836
Dividends Paid,0.741595,0.057692,0.472744,0.092322
Effect Of Exchange Rate Changes,-3.775510,-1.352941,NaN,NaN
Investments,NaN,-11.511628,-2560.571429,NaN
Net Borrowings,1.434113,-4.555887,12.043382,5.271758
Net Income,0.539540,0.280936,2.391622,-1.181746
Other Cash Flows from Financing Activities,20.422018,0.775424,0.625000,-0.043186
Other Cash flows from Investing Activities,-43.250000,39.652174,20.187500,1.134146
Total Cash Flow From Operating Activities,0.633349,-0.187723,0.106295,-0.012489
Total Cash Flows From Financing Activities,1.923143,-1.036977,-3.285877,-1.438114
Total Cash Flows From Investing Activities,-0.208330,1.662359,5.627815,0.757147

In [33]:
portfolio.balance_sheet(ATD.bs_list)

In [34]:
portfolio.balance_sheet.dropna(how='all')

,ATD-B.TO,L.TO,MRU.TO,EMP-A.TO,Averages
Accounts Payable,0.789544,0.087037,0.357665,0.148774,0.345755
Capital Surplus,0.317568,0.049020,0.127778,0.120000,0.153591
Cash And Cash Equivalents,0.178512,0.046169,9.553488,1.090291,2.717115
Common Stock,0.010003,-0.087760,1.977720,0.001369,0.475333
Deferred Long Term Asset Charges,0.866091,0.090909,-0.853420,-0.049366,0.013554
Deferred Long Term Liability Charges,NaN,NaN,NaN,-0.856164,-0.856164
Goodwill,2.204997,0.042857,0.709656,0.573546,0.882764
Intangible Assets,0.249372,-0.149062,6.685654,0.165112,1.737769
Inventory,0.797110,0.111291,0.333536,0.120019,0.340489
Long Term Debt,0.905764,-0.377013,1.337873,-0.027367,0.459814
Long Term Investments,0.434286,-0.757812,-0.787821,-0.017011,-0.282090
Minority Interest,NaN,3.538462,-0.776691,0.348562,1.036778
Net Receivables,0.444452,0.100122,0.839644,-0.069926,0.328573
Net Tangible Assets,-0.086107,-3.925926,-2.724677,-0.200677,-1.734347
Other Assets,-0.018338,-0.143158,0.726087,-0.058416,0.126544
Other Current Assets,20.470588,6.944444,NaN,-0.952100,8.820977
Other Current Liabilities,0.620500,0.203898,4.591489,-0.243243,1.293161
Other Liabilities,0.349335,-0.276638,2.269918,0.187509,0.632531
Other Stockholder Equity,0.235362,1.130435,-0.057692,-0.050505,0.314400
"Property, plant and equipment",0.746826,-0.434065,0.712870,-0.074157,0.237869
Retained Earnings,0.803522,-0.067969,0.902413,0.242111,0.470019
Short Term Investments,NaN,0.468750,NaN,NaN,0.468750
Short/Current Long Term Debt,44.528662,0.709130,-0.304000,-0.914384,11.004852
Total Assets,0.843300,-0.122362,1.027473,0.050763,0.449793
Total Current Assets,0.499514,0.180822,0.634240,0.013594,0.332042
Total Current Liabilities,1.098654,0.205206,0.536661,-0.014083,0.456610
Total Liabilities,0.858687,-0.153440,1.083592,0.011713,0.450138
Total stockholders' equity,0.770090,-0.076959,1.134675,0.104694,0.483125
Treasury Stock,0.235362,1.130435,0.503759,-0.050505,0.454763

In [35]:
portfolio.financials(ATD.fin_list)

In [36]:
portfolio.financials.dropna(how='all')

,ATD-B.TO,L.TO,MRU.TO,EMP-A.TO,Averages
Total Revenue,0.731389,0.028616,0.176672,0.020850,0.239382
Cost of Revenue,0.778945,-0.008018,0.170662,0.021285,0.240718
Gross Profit,0.511946,0.124027,0.228347,0.019515,0.220959
Selling General and Administrative,0.481009,0.133681,0.157284,0.021302,0.198319
Others,NaN,NaN,0.000000,NaN,0.000000
Total Operating Expenses,0.741463,0.026903,0.173448,0.021289,0.240776
Operating Income or Loss,0.534197,0.068559,0.231175,0.004243,0.209543
Total Other Income/Expenses Net,4.068768,0.318681,-589.714286,-0.975441,-146.575569
Earnings Before Interest and Taxes,0.534197,0.068559,0.231175,0.004243,0.209543
Interest Expense,2.118474,-0.310345,0.877224,-0.239895,0.611365
Income Before Tax,0.379002,0.420063,2.051727,-1.219375,0.407854
Income Tax Expense,-0.068792,0.646739,1.222084,-1.326988,0.118261
Minority Interest,-0.211315,3.538462,-0.776691,0.348562,0.724754
Net Income From Continuing Ops,0.528706,0.278438,2.309262,-1.196917,0.479872
Discontinued Operations,NaN,-0.796537,NaN,NaN,-0.796537
Net Income,0.539540,0.280936,2.391622,-1.181746,0.507588
Net Income Applicable To Common Shares,0.539540,0.275804,2.391622,-1.181746,0.506305

In [37]:
GP = DataFrame(portfolio.financials.dropna(how='all').T.sort_values('Gross Profit', ascending=False)['Gross Profit'])

In [38]:
statistics_df = portfolio.statistics.dropna(how='all').T.sort_values("Diluted EPS (ttm)", ascending=False)[['Diluted EPS (ttm)', 'EBITDA', 'Levered Free Cash Flow (ttm)', 'Beta (3Y Monthly)', 'Profit Margin','Trailing Annual Dividend Yield 3']]

In [39]:
Debt = portfolio.balance_sheet.dropna(how='all').T.sort_values('Long Term Debt', ascending=False)['Long Term Debt']

In [40]:
NI = portfolio.cashflow.dropna(how='all').T.sort_values("Net Income", ascending=False)['Net Income']

In [41]:
pandas.concat([statistics_df, NI, Debt, GP], axis=1, sort=True).sort_values('Gross Profit', ascending=False)

,Diluted EPS (ttm),EBITDA,Levered Free Cash Flow (ttm),Beta (3Y Monthly),Profit Margin,Trailing Annual Dividend Yield 3,Net Income,Long Term Debt,Gross Profit
ATD-B.TO,3.390,358.00,NaN,0.310,3.2800,0.4100,0.539540,0.905764,0.511946
MRU.TO,2.690,132.00,345.910,0.000,4.1400,1.3500,2.391622,1.337873,0.228347
Averages,2.415,233.75,345.545,0.095,2.6725,1.1425,NaN,0.459814,0.220959
L.TO,2.160,344.00,NaN,0.290,1.7400,1.6200,0.280936,-0.377013,0.124027
EMP-A.TO,1.420,101.00,345.180,-0.220,1.5300,1.1900,-1.181746,-0.027367,0.019515

In [51]:
ATD.earnings_est

,Current Qtr. (Oct 2019),Next Qtr. (Jan 2020),Current Year (2020),Next Year (2021)
Earnings Estimate,,,,
No. of Analysts,9.00,9.00,11.00,11.00
Avg. Estimate,0.91,0.78,3.30,3.50
Low Estimate,0.84,0.69,3.17,3.03
High Estimate,1.01,0.95,3.54,3.73
Year Ago EPS,0.84,1.08,3.32,3.30

In [53]:
L.earnings_est

,Current Qtr. (Sep 2019),Next Qtr. (Dec 2019),Current Year (2019),Next Year (2020)
Earnings Estimate,,,,
No. of Analysts,8.00,8.00,10.00,10.00
Avg. Estimate,1.26,1.15,4.21,4.70
Low Estimate,1.22,1.07,4.08,4.61
High Estimate,1.35,1.19,4.35,4.79
Year Ago EPS,1.49,1.07,4.60,4.21

In [43]:
ATD_A.stats()

In [44]:
ATD_A.balance()

In [45]:
ATD_A.financial()

In [46]:
ATD_A.cash()

In [47]:
ATD_A.analyze()

In [48]:
ATD_A.statistics

                                                   ATD-A.TO
Market Cap (intraday) 5                         4808.000000
Enterprise Value 3                              5693.000000
Trailing P/E                                      25.600000
Forward P/E 1                                           NaN
PEG Ratio (5 yr expected) 1                             NaN
Price/Sales (ttm)                                  0.820000
Price/Book (mrq)                                   5.200000
Enterprise Value/Revenue 3                         0.970000
Enterprise Value/EBITDA 6                         15.890000
Beta (3Y Monthly)                                  0.310000
52-Week Change 3                                  28.980000
S&P500 52-Week Change 3                            3.530000
52 Week High 3                                    88.700000
52 Week Low 3                                     59.650000
50-Day Moving Average 3                           82.160000
200-Day Moving Average 3                          81.050000
Avg Vol (3 month) 3                                0.029900
Avg Vol (10 day) 3                                 0.038800
Shares Outstanding 5                             126.910000
Float                                            437.870000
% Held by Insiders 1                                    NaN
% Held by Institutions 1                                NaN
Shares Short (Aug 15, 2019) 4                    469.000000
Short Ratio (Aug 15, 2019) 4                       0.520000
Short % of Float (Aug 15, 2019) 4                       NaN
Short % of Shares Outstanding (Aug 15, 2019) 4     0.000000
Shares Short (prior month Jul 15, 2019) 4          0.020100
Forward Annual Dividend Rate 4                     0.500000
Forward Annual Dividend Yield 4                    0.590000
Trailing Annual Dividend Rate 3                    0.350000
...                                                     ...
5 Year Average Dividend Yield 4                    0.480000
Payout Ratio 4                                    10.070000
Dividend Date 3                                         NaN
Ex-Dividend Date 4                                      NaN
Last Split Factor (new per old) 2                       NaN
Last Split Date 3                                       NaN
Fiscal Year Ends                                        NaN
Most Recent Quarter (mrq)                               NaN
Profit Margin                                      3.280000
Operating Margin (ttm)                             4.530000
Return on Assets (ttm)                             6.860000
Return on Equity (ttm)                            21.520000
Revenue (ttm)                                   5849.000000
Revenue Per Share (ttm)                          103.660000
Quarterly Revenue Growth (yoy)                    -4.200000
Gross Profit (ttm)                               919.000000
EBITDA                                           358.000000
Net Income Avi to Common (ttm)                   192.000000
Diluted EPS (ttm)                                  3.390000
Quarterly Earnings Growth (yoy)                   18.300000
Total Cash (mrq)                                 106.000000
Total Cash Per Share (mrq)                         1.880000
Total Debt (mrq)                                 964.000000
Total Debt/Equity (mrq)                           99.800000
Current Ratio (mrq)                                0.810000
Book Value Per Share (mrq)                        16.690000
Operating Cash Flow (ttm)                        323.000000
Levered Free Cash Flow (ttm)                            NaN
Adjusted Returns                                   1.903226
Total Returns                                     29.570000

[61 rows x 1 columns]

In [56]:
print("The Power of Computer Programming")

The Power of Computer Programming

In [55]:
print("Technology | Global Equity | Female Empowerment")

Technology | Global Equity | Female Empowerment